### ISSUE TITLE
Metadata rendering in post body when using pandoc

### ISSUE THREAD

**Issue by fncll** [getnikola/nikola#1425]
Using pandoc as a compiler (brand new install using `pip install nikola`) is working except that the metadata is being rendered as part of the body. 

So this post (`test-post.md`):

```
.. title: TEST POST
.. slug: test-post
.. date: 2014-09-18

Testing some _pandoc_ **functions**.
```

Is resulting in the following:

![test_post___nikola_test_site](https://cloud.githubusercontent.com/assets/1208889/4327822/c4ca2e68-3f7d-11e4-85e4-e1490e2263fc.png)

Not sure if it matters, but this is the line I have in my `conf.py` compilers and `.md` is not assigned to any other compilers:

```
"pandoc": ('.md'),
```

And pandoc version info:

```
$ pandoc --version
pandoc 1.12.3.3
```

**Comment by damufo** [comment]
Hello:

I open this thread because I think it has to do.
Sorry if I'm wrong.

theme: hack

I use markdown for posts.

when use pandoc compiler code blocks are wrap for long lines. I like this behaviour.
when use markdown compiler code block long lines no are wrapped.

How I can made markdown compiler to wrap long lines in code blocks?

pandoc
![nikola_pandoc_code_wrap_long_lines_](https://user-images.githubusercontent.com/4057369/164890503-07bede18-170f-40ac-8e5c-cdd404e4ec5a.png)

nikola built-in markdown
![nikola_builtin_markdown_code_no_wrap_long_lines](https://user-images.githubusercontent.com/4057369/164890501-72e0fc4b-c25c-4aa8-8e08-84f431619b2f.png)

**Comment by Kwpolska** [comment]
@damufo Old, closed issues are not the place to ask questions. [Please create a new Discussion with your question.](https://github.com/getnikola/nikola/discussions/new)
