### ISSUE TITLE
Enable the MultiMarkdown support

### ISSUE THREAD

**Issue by andreamoro** [getnikola/nikola#1495]
One of the limitation I found in Nikola is the way how "pages" can be built merging content from external files.

One solution is using restructuredText and it's import functionality. However ReST is limited in terms of HTML editing and requires lot of efforts to embed raw html.
On the contrary, Markdown offer a better support when it comes to the HTML code, but it doesn't support content transclusion. 

I've done some homework during the weekend, limited to some research only. Apparently solutions are already in place (in a way or another). Si it seems it's a matter of making them part of Nikola?

Have a look at these two
https://noswap.com/projects/markdownpp
https://github.com/JeNeSuisPasDave/MarkdownTools (This seems better)

An alternative it could be making Jinja changing the default path to a foler located somewhere else in the local computer. At the end of the days, static content is always the final result. However, I'm not sure this could help the project per se.

Any chance to implement this?
Thanks

**Comment by ralsina** [comment]
You are not going to get "a complete abstraction from the template (that can be done in either Mako or Jinja2) with all HTML tags under full control of the developer" unless you write your own compiler for your own markup. Ever. Because the current markup compilers do what they do, and changing that is (IMHO) both outside of Nikola's scope and just not doable at all without rewriting all of docutils HTML parts or python-markdown (or pandoc, or python-textile, etc).

A markdown extension that includes another file, that is something that is doable. Let's limit the Issue to that :-)

**Comment by ralsina** [comment]
Aaaaaand [here is one](https://github.com/cmacmackin/markdown-include). Install that, add it to the markdown extensions config, and include other markdown files at will.

Closing.

**Comment by andreamoro** [comment]
Thanks for pointing this me out Roberto?

Have you tested it? 

Once the plugin is installed, is it really the case to have {{filename}} and that's it? I mean, the example in the github project is a bit odd and it is for a standard script not for an engine.

Sorry for asking, but I won't be able to play around with the instance of Nikola for the next 5 days or so.

**Comment by ralsina** [comment]
Yes, tested it. Works at least with absolute paths, no idea how to make it find things with relative paths, and fails silently when it can't find the file you want it to include. I would raise those as issues in their bugtracker if I used it.

**Comment by Kwpolska** [comment]
PS. This is meant to be used with `MARKDOWN_EXTENSIONS`.  Like so:

```command
$ pip install markdown-include
$ vim conf.py
```

```py
MARKDOWN_EXTENSIONS = ['markdown_include.include']
```
