### ISSUE TITLE
Include links to subdirectories in gallery RSS

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1525]
Currently, the RSS feeds for galleries include only the images and no links to subdirectories — in other words, `/galleries/rss.xml` is useless, and people with complex structures may not have complete files.  It might be nice to have links to subdirectories, at least in the “top” RSS file.  Comments?

//cc @ralsina

**Comment by ralsina** [comment]
Gig problem implementing this: how do I know if it's a "new" folder? Obviously folder creation date doesn't work.

**Comment by Kwpolska** [comment]
Won’t RSS readers handle this for you if you just plainly throw items at them?

**Comment by ralsina** [comment]
No guarantees. RSS readers are very very stupid. 

What the RSS generating app is supposed to do is only add the latest things in the feed. I see no way to do that with folders.

Best case they will not show them to you each time, but you are going to end up with a feed that is larger each time you add a folder, because you will have to put them all in the feed.
