### ISSUE TITLE
Deprecate the ability to encrypt posts

### ISSUE THREAD

**Issue by cipherself** [getnikola/nikola#1547]
It appears that there's an option to encrypt posts using a password, I suggest that this option should be deprecated for a number of reasons:
- The encryption algorithm used is RC4, which has been declared insecure for a while and should not be used. [1][2][3] Also, no MAC is used which makes it vulnerable to a bit flipping attack.
- When using cryptography, it's highly advised to use an implementation that was written by experts and reviewed by multiple ones as opposed to "Rolling your own". [4]
- JavaScript cryptography is bad. [5]

I've also quickly skimmed a couple other static site generators, namely (Jekyll, Hyde, Hakyll and Frozen-flask) and I don't think they offer an option to encrypt posts.

[1] http://blogs.technet.com/b/srd/archive/2013/11/12/security-advisory-2868725-recommendation-to-disable-rc4.aspx
[2] http://www.wisdom.weizmann.ac.il/~itsik/RC4/rc4.html
[3] https://tools.ietf.org/html/draft-ietf-tls-prohibiting-rc4-01
[4] http://security.stackexchange.com/a/18198
[5] http://matasano.com/articles/javascript-cryptography/

**Comment by ralsina** [comment]
There is no way to implement this in a safe and secure manner, specially since you'd need to find two implementations of whatever crypto system you prefer, one in JS and one in Python, which are mutually inteligible and both safe.

OTOH this is meant for things like "use this password to read this review, it has spoilers" rather than "here are the diagrams to my secret terror weapon, don't tell anyone".

The feature not being in other SSGs is hardly important, and as long as it breaks nothing (and it doesn't) I don't see why it needs removing. Unless you actually use it, it will do *nothing* to your output.

**Comment by ralsina** [comment]
OTOOH I could reimplement this as a restructured text directive which is niftier and would allow it to be a plugin cleanly.

**Comment by devurandom** [comment]
> I found a total of two actual posts using this feature all over the Internet. (not posting links here for the safety of those people)

I tried to use it once. I think to create two views of my blog, for different groups of people. It did not work out very well for some reason, so I removed the pages instead.

I think initially I tried it also for general access control, but then ran into some kind of wall. Thus I went with HTTP Basic authentication instead. I manage it through (manually set up) Mercurial post-receive hooks. The result looks a lot more technical and ugly than an in-page password field might, is not very nice to setup, but it was ok for my usecase.

**Comment by toolforger** [comment]
For hiding spoilers, people should simply use white-on-white text and tell users to mark the spoilerish part of the page.
Javascript is going to sit badly with security-aware visitors, and Nikola is designed to allow more security in the net after all (though I'll admit that's visitor security, and Nikola is about server security, so that's not a killer criterion).
