### ISSUE TITLE
Diable LICENSE in some pages?

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#1608]
It does not make sense to display LICENSE in an about page. Is there a way to disable LICENSE in some pages? If not, I think it's a nice feature to be added.

**Comment by Kwpolska** [comment]
First off, `LICENSE` is displayed by `CONTENT_FOOTER`.

You would basically need to create a special template for the about page that does not display this part of the footer, which would require displaying `LICENSE` independently of `CONTENT_FOOTER`, and only on pages where you want to see it.

**Comment by xuhdev** [comment]
@Kwpolska Just asking, are you going to do something about this in 7.3.1, or this is the answer? I see you closed this issue and marked a milestone, which confused me.

I think this question can be extended in a way to license each post under different license. Maybe it's a good idea to design a good licensing system, or simply allow user to add a custom snippet after each post, see [my post on the mailing list](https://groups.google.com/forum/#!topic/nikola-discuss/u324RrPRyCE).

**Comment by Kwpolska** [comment]
We are not going to change this, it’s impossible right now (especially in v7.3.1, a bugfix release).  And each issue gets a milestone, just because.

About this snippet thing, modifying templates really is the way to go.  It’s hard to produce something that will work everywhere and for everyone.  Writing your own templates (you don’t even need a theme if you just throw .tmpl’s in a templates/ directory in your site) is easy and fun, and the possibilities are endless.
