### ISSUE TITLE
Document the global variables that can be used for templates

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#1611]
The [global variables](https://github.com/getnikola/nikola/blob/ffd75d5124f848d3b74f97256441f3a369b3f384/nikola/nikola.py#L680) are currently not documented. It would be a good idea to document them, thus template making would be easier.

**Comment by Kwpolska** [comment]
Most of them **are**, we consider [the config file](http://getnikola.com/conf.html) part of the documentation.  The remaining few are functions, most of which have docstrings; and some other variables that have self-explanatory names or are otherwise easy to decrypt by reading the code.  We do not have any variables that live “alone” (other than the two variables for the reveal theme, which should not really be there)  Otherwise, the variables are either config entries (again, documented in `conf.py.in`) or functions (which hopefully have docstrings).

Even if we were to create a special document, there are tons of variables, and we will probably forget to keep the file up-to-date with every change. Besides: there are also local (template-specific) variables you need to take care of (which are partially documented in the theming doc).  *We recommend starting with the `base`/`base-jinja` template and looking how that template implements something.*

The best thing in Nikola and Python is that you can always **experiment** with things — either in the live template, or in the very safe and friendly environment of `nikola console` (which is even friendlier if you have `ipython` or `bpython` installed in the same virtualenv as Nikola, which you totally should)

**Comment by randomhammer** [comment]
The kind of people who are likely to write good themes are not the kind of people who will happily go through Python source code to decrypt things. Writing good themes is hard enough when you can't figure out what the environment looks like.
