### ISSUE TITLE
nikola 7.3.0 no  Syntax Highlighting？

### ISSUE THREAD

**Issue by nicebug** [getnikola/nikola#1636]
hi  my nikola version is 7.3.0，i made a markdown file with a code block:
but there is no *Syntax Highlighting*
![image](https://cloud.githubusercontent.com/assets/1947907/6705646/f343bce4-cd91-11e4-9778-d1d6591ea1b5.png)

is there any way to show my code like github wiki with Syntax Highlighting. like this:
![image](https://cloud.githubusercontent.com/assets/1947907/6705659/23b5eae6-cd92-11e4-8c46-8d32fe9682ea.png)

**Comment by nicebug** [comment]
sorry i have solved

**Comment by SeanZicari** [comment]
How did you solve this?

**Comment by Kwpolska** [comment]
What theme, what reST code, what code color scheme are you using?

-- 
Chris Warrick <https://chriswarrick.com/>

On Nov 30, 2017 16:23, "Sean Zicari" <notifications@github.com> wrote:

How did you solve this?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/getnikola/nikola/issues/1636#issuecomment-348220445>,
or mute the thread
