### ISSUE TITLE
suggest command names

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1807]
If you say "git chkout" it will say you probably mean checkout. How is that done? Can we do it? Is it worth it?

**Comment by Kwpolska** [comment]
a quick look through the `git` source code hints at Levenshtein distance with:

```c
#define SIMILARITY_FLOOR 7
#define SIMILAR_ENOUGH(x) ((x) < SIMILARITY_FLOOR)
```

**Comment by ralsina** [comment]
That should be easy enough.

**Comment by Aeyoun** [comment]
I was thinking about this just yesterday. :+1:

**Comment by ralsina** [comment]
See https://github.com/getnikola/nikola/pull/1808

**Comment by ralsina** [comment]
Done in #1808

**Comment by felixfontein** [comment]
I today accidentally ran `nikola plugins` instead of `nikola plugin`, and Nikola took around 36 seconds to tell me that I might have meant `"plugin"`. The problem is that the `lev()` function is very slow for longer arguments, for example only the one call
```
lev('import_wordpress', 'plugins')
```
takes several seconds to finish. As written in the thread where this function is copied from, the implementation we use is pretty bad.
I suggest we use the implementation from here: https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#Python which is alsy very efficient (i.e. returns with no noticeable delay) on larger inputs.

**Comment by Kwpolska** [comment]
I swapped the algorithm for the first one on Wikibooks (and it’s MUCH faster), made the output a bit prettier and banned `run` in commit 2466123.

**Comment by felixfontein** [comment]
Cool, thanks :)
