### ISSUE TITLE
Use watchdog in auto

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1810]
Someone else suggested it a while ago, and I (wrongly) didn't even look at it. It would make auto more crossplatform, and simpler, at the cost of a changed dependency.

**Comment by schettino72** [comment]
I am also considering moving `doit` from pyinotify to watchdog. But note it is not just *one* dependency change because watchdog depends on yaml and a bunch of stuff... https://github.com/gorakhargosh/watchdog/issues/297

**Comment by Kwpolska** [comment]
We don’t really mind, especially since it’s going in `extra` dependencies.

**Comment by ralsina** [comment]
Yaml is actually for a commandline tool it comes with (watchdo?) so maybe that can be skipped.

**Comment by schettino72** [comment]
That's the problem. Since there is no separate package for the command line tool. Nikola will not be able to skip that. 

The solution would be the `watchdog` project release the lib separate from the command line tool or provide the command line tool as a setuptools extra. So it is up to `watchdog` to fix the issue (or anyone willing to manage a fork in another package on pypi without the command line tool).

**Comment by ralsina** [comment]
@schettino72 want me to bug them about it, or you want to do it? :-)

**Comment by schettino72** [comment]
@ralsina please go ahead :+1:

**Comment by ralsina** [comment]
Issue already existed, commented on it: https://github.com/gorakhargosh/watchdog/issues/297
