### ISSUE TITLE
meta tag generator

### ISSUE THREAD

**Issue by humitos** [getnikola/nikola#1855]
I just noticed that there is a meta tag with name "generator" to identify the software used to generate the webpage. I think we should added it:

http://www.w3.org/TR/html5/document-metadata.html#standard-metadata-names

```
<meta name="generator" content="Nikola 7.5.1">
```

**Comment by Aeyoun** [comment]
It doesn’t really add any value, does it?

**Comment by Kwpolska** [comment]
Do humans look at this tag?  I don’t think so.  This probably won’t help with promotion or anything.

And if we were to include the version, this would be a huge burden on the maintainers, because we would have to rebuild invariance on every Nikola release — and our [tasklist](https://github.com/getnikola/releng/blob/master/src/checklist.md) is already massive…
