### ISSUE TITLE
Getting the title from rest titles is broken.

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1895]
This used to produce a post with title  "Write your post here." via get_metadata_from_file and now it doesn't anymore.

```
.. slug: asda
.. date: 2015-07-17 13:07:03 UTC
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

Write your post here.
=====================


sdfasdfasdf
```

Only found this when fixing a pile of broken tests for the  mock 1.1.4 switch.

**Comment by ralsina** [comment]
It fails because of the empty line before the title:

```
>>> from nikola.post import _get_metadata_from_file as g
>>> d = ['.. slug: write-tests-now', '.. date: 2012/09/15 19:52:05', '.. tags:', '.. link:', '.. description:', '', 'Post Title', '----------']
>>> g(d)
{'date': '2012/09/15 19:52:05', 'slug': 'write-tests-now'}
>>> d=['.. slug: write-tests-now', '.. date: 2012/09/15 19:52:05', '.. tags:', '.. link:', '.. description:', 'Post Title', '----------']
>>> g(d)
{'date': '2012/09/15 19:52:05', 'slug': 'write-tests-now', u'title': 'Post Title'}
```

**Comment by Kwpolska** [comment]
This magic, at least on the current master, seems to crop down input files with some magic.  I hit this error while working on the redesigned website. One of my HTML input files had no metadata (tidy drops comments at the top of file), and yet it decided to find the metadata. It inferred slug from the filename, skipped date (not needed on pages).  And then it decided to **throw away 175 lines**.  Why?  Because lines 174-177 look like this:

```html
        <pre class="gs-console">
<code>$ <span class="gs-command">nikola init --demo my_first_site</span>
Creating Nikola Site
====================
```

(also, this is `.html`, not `.rst` nor `.md`!)

**Comment by ralsina** [comment]
Yes, it's not the smartest piece of code around these parts.
