### ISSUE TITLE
Post.title() returns chunks of JSON for some IPython NB

### ISSUE THREAD

**Issue by Mec-iS** [getnikola/nikola#1904]
I noted that most of the time [this method](https://github.com/getnikola/nikola/blob/master/nikola/post.py#L337) returns chunked JSONs like `"source": [` or other wrong strings, instead of a proper title of the post.

I couldn't understand how you set the `self.meta` property so I patched the returning string in a more straightforward way, leveraging the Python `title()` method:
```
return self.meta[lang]['slug'].replace("-", " ").title()
```
Probably there is something in the way the code sets the `self.meta.en.title` property that doesn't like too much stringified JSONs or stuff.
Cheers!

**Comment by Kwpolska** [comment]
I reproduced a similar issue. It was caused by our favorite bit of fragile code: the reST/Markdown underlined title getter, and `nikola.post.get_meta()` (hint, hint!), which tries to do a little too much.

I fixed it by not getting file metadata if we have compiler metadata already. And yet I still don’t understand how the getter hack transformed this:

```json
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Hello!\n",
    "======"
   ]
  }
 ],
```

into this (with spaces and `"` in the way!):

```py
{'title': '"Hello!\\n",'}
```

Also, we have `nikola.utils.unslugify()` for workarounds like yours.

**Comment by ralsina** [comment]
On 22/07/15 04:30, Chris Warrick wrote:
>
> I reproduced a similar issue. It was caused by our favorite bit of 
> fragile code: the reST/Markdown underlined title getter, and 
> |nikola.post.get_meta()| (hint, hint!), which tries to do a little too 
> much.
>

That needs a condition added to only get rest titles for rest posts and 
md titles for md posts. I have it in my TODO but I am not going through 
it very fast...
