### ISSUE TITLE
Default to non-relative URLs?

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#1922]
Relative URLs can create problems, eg. missing assets. We could switch `URL_TYPE` to `full_path` (root-relative) for new sites to work around them.

Comments, opinions, counter-arguments?

@Aeyoun
cc @ralsina

**Comment by Aeyoun** [comment]
Just to be clear: `<base href="${canonical}">`. This produces the same as using the web browser’s default fallback base URL even when the document is loaded from a path or even a host different from the canonical link (that is the point where resources and links start breaking).

* Relative URLs need a base element to compensate for over permissive path-matching on servers
* Root-relative only really benefit from having a base element when loaded from a different host (like localhost or a scraper)
* Relative and root-relative both load resources and have working links when documents are either downloaded to local computer OR served from a different server than it’s origin. (Minor.)
* Absolute URLs everywhere never see any benefit from having a base element

Recommendation alternative 1:
Keep current relative URLs and add a canonical link as base element. Smallest change.

Recommendation alternative 2:
Leave out base element and

Nikola’s canonical URL is already well-tested on all page types and are perfectly suited to be used as is in templates (well, except galleries because I don’t use them.)

Examples of URLs where all resources and links break without picking one of the above (hosted from Apache, nginx, or ISS default setup):
* /posts//example.html
* /errors/404.html loaded as /where/is/this/anyway
* /posts/pretty-url//

W3C’s link checker can be used for extensive automated testing of all anchors and links for anyone who want to test out setting a base element  on their site:
https://validator.w3.org/checklink

PS: People complaining that setting base break thing usually set the base to the canonical link’s dirname and not the canonical link itself.

**Comment by ralsina** [comment]
"Relative and root-relative both load resources and have working links when documents are either downloaded to local computer OR served from a different server than it’s origin. (Minor.) "

That's "nikola serve" and "nikola auto", so, not minor.

I have not seen yet an example of where this is currently broken.

**Comment by Aeyoun** [comment]
https://chriswarrick.com//fo/ur/oh/fo/ur
https://chriswarrick.com/blog/2015/07/06/upass//

**Comment by ralsina** [comment]
The second one violates RFC 1630 AFAICS :-)

**Comment by Aeyoun** [comment]
@ralsina, maybe. But then again http://apple.com/..///.././ipad//.//../

**Comment by Aeyoun** [comment]
The serve and auto commands shouldn’t have a problem with setting a base URL anymore. Is there anywhere else where this would be a problem? If not we should either change default to absolute or root-relative, or leave it as it is but add a base element.

**Comment by ralsina** [comment]
Let's go with the  base element. Worst case we can undo.

**Comment by Aeyoun** [comment]
Should only break if anyone have set their URLs incorrect in config. Then other things will be broken too (sitemaps, rss, etc.). This just makes it more obvious right away that things may be broken.

**Comment by DadAtH-me** [comment]
How should this be set for sites that can serve either http and https content? I've been migrating sites to https as they come up, additionally I've started using https anywhere.

If you enter the the site without http(s) it builds the URL paths as relative. If you use http then any https content doesn't get served.

**Comment by Aeyoun** [comment]
You should redirect one to the other. Having the same content on two protocols, even on the same domain, is considered separate origins with will run you afoul of the search-engine’s no-duplicated-content policies. So decide on either HTTP or HTTPS and have all your links use one or the other.
