### ISSUE TITLE
Moving listings don’t rebuild the sitemap

### ISSUE THREAD

**Issue by Aeyoun** [getnikola/nikola#2017]
LISTINGS_FOLDERS = { "projects/snippets": "projects/snippets" }

    touch projects/snippets/example/test.1
    nikola build
    mv projects/snippets/example/test.1 projects/snippets/example/test.2
    nikola build
    nikola check --clean-files
    nikola check -l

Broken link /projects/snippets/example/test.1 found in sitemap.xml. Projects/snippets/example/test.2 is not in the sitemap.

**Comment by ralsina** [comment]
I think the problem is not what you think, and/or I can't reproduce this correctly.

* If I move a file inside listings, I do get the site rebuilt, and the new output file appears in sitemap.

* The old file *still* appears in sitemap, but that's ok, because it's still in output and sitemap reflects reality

* If you do a --clean-files then yes, the old file is in sitemap but not there in reality, and rebuilding the site will do nothing.

So, maybe --clean-files should offer to rebuild the sitemap and/or mark the sitemap as dirty somehow so a rebuild will recreate it?
