### ISSUE TITLE
Think about generalization of taxonomies.

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2107]
So, we have a post / page. It has a tag. Then we:
- Create a list of tags
- Create a list of things for each tag
- Link from the post to the tag

Then the post has an author. We:
- Create a list of authors
- Create a list of things for each author
- Link from the post to the author

And then there are sections. We:
- Create a list of sections
- etc, etc etc.

This feels to me like it has reached a tipping point of special cases, and needs to be refactored into something that:

1) Has a function to classify posts per "something"
2) Provides a list of the different somethings in all the posts
3) Can create a link to a specific something.

Am I right?

**Comment by Aeyoun** [comment]
You’re probably right. There is also the issue of having different code to sort and filter lists based on draft and other properties, and language all over the place. Lots of duplicated logic and chances for things to go wrong in different ways.

**Comment by ralsina** [comment]
Plus "posts_per_tag" and all its cousins hanging off the Nikola object... so unseemly :-)

**Comment by teknico** [comment]
This is about implementation, but I'll add something about specs anyway.

As discussed on IRC, I'm glad categories are going away: they're redundant with sections, which are better anyway (thanks @Aeyoun!).

The one thing only categories have, though, is a hierarchical structure, which would actually be more useful on tags. I'd like to suggest making tags hierarchical, possibly with a fixed maximum depth if it simplifies implementation. Three levels should be enough for everyone. ;-)

Then, at least part of the tags' implementation is going to be separate from, or additional to, the other "somethings", because authors and sections are most likely not going to need hierarchies.

**Comment by Kwpolska** [comment]
Hierarchical sections are pretty logical, especially if they come from the underlying directory structure.  (it would need more work to prevent #2023 though — opt-in, patterns, limits, looking at POSTS and finding a common ancestor?)

**Comment by teknico** [comment]
Well, they would be logical but maybe less than useful, as hierarchical categories are.

I concur with @Aeyoun in trying to keep sections to very few: you can put a post in just one section (and category, fwiw), and sometimes it's hard to decide which place of a fine-grained hierarchy a post should occupy.

Tags don't have that problems, since you can have several on the same post, so it's easier and more useful to have hierarchies on them instead.

**Comment by felixfontein** [comment]
How about a general system which can be plugin-ed? A plugin for it (or a handler, or whatever) should:
 - provide a method to extract a path (or several paths) per post and language (a path instead a single name helps creating/modelling a hierarchy);
 - general info about whether there's precisely one such category per post, or multiple (zero or more);
 - provide config on how to render pages for each node (like use post-lists or indices, base path where to put results, prefix for first path part, ...)
 - provide a method to get titles for indices and post.

Using such an interface a very general scheme supporting tags, tags with hierarchies, categories, sections, time-based archives (path equals `[year, month]`), author overview page and posts per author, ... could be implemented very generally.
(Actually, that's more general and somewhat similar to the extended tag support I've been thinking of in #2039.)

**Comment by felixfontein** [comment]
The hardest part of implementing this feature right now is that some taxonomies, more precisely: tags and categories, possibly share a overview page (they do so by default). So either we add support for this right from the beginning, which will make things pretty complicated, or we start by deprecating categories and not allowing this, which would make it rather straightforward to implement this. (We could also keep this feature in a branch until v8 is coming up, to avoid implementing special stuff for tags+categories, but this would be quite annoying... Keeping a branch up-to-date for a long time isn't much fun.)
What do you think?

**Comment by felixfontein** [comment]
Ok, I finished a first experimental version of a generic taxonomy plugin in #2535. The main result is a new plugin category, `Taxonomy` (https://github.com/getnikola/nikola/blob/generalization-of-taxonomies/nikola/plugin_categories.py#L457), which contains quite a lot of stuff (to be very flexible and cover a log of corner cases in existing plugins), as well as conversion of most existing taxonomies to this new format. The only taxonomies missing are tags and categories, as they are inherently linked by the shared overview page. (Once that restriction is gone, conversion should be trivial, though.)

So far, the code size increased (partially due to long comments in the plugin interface), but I think the result is worth it: it is much easier to understand what the taxonomy plugins actually classify and it is also very simple to change them, like adding support for section hierarchies or hierarchical tags.

Any comments/ideas/...?

**Comment by Kwpolska** [comment]
> which contains quite a lot of stuff (to be very flexible and cover a lot of corner cases in existing plugins)

How many corner cases are there, and how many of them we could reasonably get rid of?

**Comment by felixfontein** [comment]
Some corner cases are:
 - Tags and categories are the only taxonomies which generate Atom feeds for post lists;
 - Page index and archive never generate RSS feeds; all other taxonomies obey the `GENERATE_RSS` config (for page index that makes perfect sense, though);
 - The archives plugin has a very strange logic when to omit empty archives (I think that's kind of an error, since it might result in broken links to non-existing feeds);
 - Tags and categories are the only taxonomies which create taxonomy pages for all tags and categories from all languages in all languages (because they work with language-indepdenent `site.posts_per_tag` and `site.posts_per_category` dicts);
 - The main index taxonomy is the only one where `get_path` needs to be able to specify page numbers;
 - The biggest variety exists when creating paths:
   - The main index, the page index and section indices always want `INDEX_FILE` appended;
   - The main archive page never wants `INDEX_FILE` appended, while all other archive pages (for years, months and days) want it appended;
   - The authors, tags and categories taxonomies want `INDEX_FILE` appended for `.html` files and when `PRETTY_URLS` is enabled; for feeds and when `PRETTY_URLS` is disabled, they want to use the last component of the path appended with the correct file extension.

Some of these can be changed easily (fixing the strange archive behavior should be the most obvious and least problematic). Getting rid of most of the other particularities results in some sites being built differently which might produce broken links and other damage, so I'm not sure whether that's a good idea.

**Comment by felixfontein** [comment]
(I think these were all of them. But don't nail me on that :) )

**Comment by felixfontein** [comment]
Any more comments? @ralsina, what do you think? How does this compare to what you were hoping for?

**Comment by felixfontein** [comment]
Do you want to keep this issue open, or should we close it (as #2535 is now merged)?

**Comment by Kwpolska** [comment]
It’s done, so let’s close it.
