### ISSUE TITLE
NIkola does not see plugins listed under DISABLED_PLUGINS

### ISSUE THREAD

**Issue by polyzen** [getnikola/nikola#2139]
First noticed while running `nikola build`:
`ERROR: _switch to py3:please!. Task dependency 'sitemap' does not exist.`

> polyzen> there's no longer a way to disable the sitemap? i don't see it under `nikola plugin --list-installed` nor `nikola list` unless it's part of render_site
> +ralsina> sitemap at /home/ralsina/Desktop/proyectos/nikola/master/nikola/plugins/task/sitemap/
> +ralsina> I suspect disabled plugins are not listed anymore, try that in some other folder
> polyzen> ah yes

**Comment by Kwpolska** [comment]
There are two different problems here:

1. `DISABLED_PLUGINS`:

  a. Listing plugins bases off plugins that are enabled → hard to fix, and we probably won’t do it
  b. Listing tasks bases off plugins that are enabled → won’t fix, because it would require a huge architecture change

2. You disabled the sitemaps plugin, and our py2 warning depends on it.

**Comment by polyzen** [comment]
After removing robots and sitemap from disabled plugins, I no longer get an error like this.
`DISABLED_PLUGINS = ["render_archive","render_galleries","render_indexes","render_listings","render_tags"]`

**Comment by Kwpolska** [comment]
The error appeared because

> You disabled the sitemaps plugin, and our py2 warning depends on [the sitemap task so the warning is shown in nikola build as the last thing].

**Comment by ralsina** [comment]
@Kwpolska Yes, but that's not what this issue is about :-)

Before I worked on loading only the needed plugins, they would all appear on --list-installed and now they don't.
