### ISSUE TITLE
Add support for Civil

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2162]
https://civilcomments.com/we-are-civil/

**Comment by Kwpolska** [comment]
Do we really need support for every comment system in the world?  How is this better than any of the systems we already support?

**Comment by ralsina** [comment]
Do we? No. Do I want to? Not really. If it's not much of a bother, why not?

**Comment by tritium21** [comment]
Is it currently impossible to implement comment systems via plugins?  If it isn't then adding more comment systems feels like something prime for the plugin system, and might-should go there instead of in the core.  If it IS impossible, maybe, possibly, some day, make the comment system just be plugin based?

**Comment by Kwpolska** [comment]
Right now, we’re dispatching handlers via a template. We would need to change it so that plugins can inject their own handlers.

**Comment by Kwpolska** [comment]
Closing because this service clearly hasn’t even taken off, with a grand total of 702 followers on Twitter.
