### ISSUE TITLE
nikola init should fail fast on existing target directory

### ISSUE THREAD

**Issue by bzamecnik** [getnikola/nikola#2214]
When I run `nikola init --demo .` and fill all the stuff an error is thrown: `FileExistsError: [Errno 17] File exists: '.'`.

The problem is that I have to fill in all the details again. The app should first check the directory and fail fast so that the user can fix the problem and THEN fill in the details.

**Comment by Kwpolska** [comment]
This is a bit hard to solve. The best solution IMO is to reject `.` as input. `nikola init --demo` uses `shutil.copytree` internally, which in turn uses `os.makedirs()` with `exist_ok=False`, which leads to this error. There is [an issue about it](https://bugs.python.org/issue20849) on the Python bug tracker, but it’s pretty dead.

Since you should not mix your Nikola site with anything else, you should ask Nikola to create the directory instead of doing it yourself. Rejecting `.` makes sense.

Opinions?

**Comment by bzamecnik** [comment]
Thanks for a quick reply. Yeah it makes sense to reject `.`. But still when I create a new git repo, run `nikola init foodir`, then I would have to move contents of `foodir` to the repo root. Or is it a bad practice and I should still have the site in `foodir`?

**Comment by Kwpolska** [comment]
Your Nikola site should live in the repo root. You should just change who gets to create the directory.

```
$ nikola init foodir
$ cd foodir
$ git init .

**Comment by bzamecnik** [comment]
Aha. That was the problem. I created a repo on GitHub, cloned it and then ran `nikola init`. Thanks for clarification.
