### ISSUE TITLE
import_wordpress don't convert to markdown

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2261]
import without errors

text from XML `<content:encoded>` is copied with a newline after each line.

export: https://davidak.basecom.de/paste/?dc58ba722a84925a#fTZSvcajZOpwJv5uhFRSe7vLARmWCqhtL7497BObAto=

![bildschirmfoto 2016-02-23 um 17 09 25](https://cloud.githubusercontent.com/assets/91113/13257836/b6594eda-da50-11e5-8bc1-06b24e75ac81.png)

**Comment by davidak** [comment]
also reproducible with fresh installed wordpress and pages.

[demosite.wordpress.2016-02-23.xml.zip](https://github.com/getnikola/nikola/files/143073/demosite.wordpress.2016-02-23.xml.zip)

**Comment by felixfontein** [comment]
The reason why this happens is here: https://github.com/getnikola/nikola/blob/master/nikola/plugins/command/import_wordpress.py#L385 as `line` already contains an `'\n'`. Replacing this line with `return b''.join(xml)` should fix this.

@Kwpolska, since you wrote that part: is there a reason why the extra newlines are needed?

**Comment by Kwpolska** [comment]
They are probably not needed and just a bug. Feel free to remove that.

**Comment by felixfontein** [comment]
Ok, I created a PR for that part.

I don't understand the "don't convert to markdown", though. @davidak, did you only mean that additional newlines are introduced, or did you mean something else as well?

**Comment by davidak** [comment]
@felixfontein thanks!

take a look at my screenshot. the upper editor window shows the current result. it's plain HTML, not markdown.

**Comment by felixfontein** [comment]
Sorry, I overlooked the screenshot (had no RequestPolicy role for cloud.githubusercontent.com yet).

Well, the default "conversion" of WordPress posts to MarkDown was always quite strange (from my point of view); it does some little things and then runs the content through a HTML parser (lxml) and lets it output its state. That's why the output is so "strange". Since MarkDown allows HTML, this is probably kind of ok. It looks really ugly, though.

(That was also one of the main reasons why I started hacking around and finally created the WordPress compiler plugin, since I didn't want such a conversion which screws up the post sources in this way.)

So it's not really a bug, but a "feature". Fixing this requires a lot of effort.

(Your blog post also shows why it is so hard to work with WordPress posts: they can contain any random usage of HTML tags, like `<li>...</li>` without `<ul>...</ul>` and `<ol>...</ol>`. Converting such a mess correctly to another markup language is really, really hard. That's why I simply took the original WordPress conversion code and converted it to Python for the compiler plugin, so that it wouldn't try to convert anything but just use the same code as WordPress to render the result as HTML, so that the resulting HTML included in the blog output should at least be "as expected".)

**Comment by davidak** [comment]
what is wrong with the link or the more-tag?

i would call this a serious problem.

i found a solution with Exitwp and the Nikola Jekyll import. there will be a documentation on my new site.
but this should get fixed if you want to promote the wordpress import.

**Comment by ralsina** [comment]
@davidak plain HTML *is* valid markdown. The conversion basically takes some of the not-HTML things WP does and converts them into markdown, and leaves the rest as-is.

**Comment by davidak** [comment]
The Documentation of my Workaround is here: https://github.com/davidak/davidak.de/blob/master/pages/wordpress-artikel-nach-markdown-und-restructuredtext-konvertieren.rst (maybe it helps someone)

**Comment by felixfontein** [comment]
Hmm, we could of course modify the WordPress importer to use html2text (either the version from https://github.com/thomasf/exitwp or the original one from http://www.aaronsw.com/2002/html2text/). Unfortunately, it is licensed under a less liberal license than Nikola core, so it cannot simply be included. One possibility would be to allow the WordPress importer to use this utility, though.

**Comment by felixfontein** [comment]
Ah, there's a PyPi package, so we can just use it this way: https://pypi.python.org/pypi/html2text

**Comment by ralsina** [comment]
@felixfontein want to take a crack at this one?
