### ISSUE TITLE
Replace umlauts with correct vokals

### ISSUE THREAD

**Issue by davidak** [getnikola/nikola#2273]
When you create a new post, umlauts in the slug don't get replaced correctly.

is: `ü -> u`

should be:
```
ä -> ae
ö -> oe
ü -> ue
```

**Comment by Kwpolska** [comment]
We can’t do that. Only German uses this rule; other languages do not allow such substitutions (opting for `o` instead).

**Comment by felixfontein** [comment]
We already had this discussion in #2172. I'd really like to see this fixed in a good way, like I suggested in that PR: pass the language to `slugify` and let `slugify` allow to extend `slugify` similar to the month name/date formatting handlers for `LocaleBorg`.

**Comment by Kwpolska** [comment]
Again: we depend on the slugify output being invariant. And considering how hard it is to get locale support right sometimes (race conditions and such), we can’t do that sensibly. We would need a lot of test coverage to make sure there are no bugs caused by trusting `slugify()` to be invariant and forgetting about a minor change for one language.

That said: you can always disarm slugify. You will get something even better: spaces, capital letters, and äöüß in your addresses.

Or even better: you could have some post-processing thing (a **signal handler**, perhaps?) that would fix your post slugs by editing it in the input files. You could even make it a plugin and put it on plugins.getnikola.com. This sounds like the best resolution for everyone: the German-speaking Nikola community gets correct slugs in the most prominent places and we don’t have to introduce even more complexity to LocaleBorg.

**Comment by felixfontein** [comment]
1. `slugify` is usually called in places where a link is generated, and there the language is always known (otherwise, how should the link be generated? or the link will be wrong anyway).

   Or is `slugify` used in another context than link / URL generation?

2. Of course you can disarm `slugify` completely, but that's usualy not what one wants. I want to restrict to ASCII letters in URLs, but I don't want screwed up umlaut transformation, either.

3. A signal handler sounds like a really, really hacky and even worse solution.

4. For languages which don't use the Latin alphabet, you might want completely different transformations and not just a fallback to UTF-8.

**Comment by Kwpolska** [comment]
Slugify is also used for “tags are too similar” feature — it might lead to some weird bugs here or there. And if we were to change the behavior now, for everyone, some URLs would be changed, maybe even without the user noticing, and might require orphan cleanup and adding custom redirects. If this was an option, it would be unpopular and untested.

And if we were to agree for one language, we would need to add hacks for all the other languages out there, and someone would chime in with a transliteration thing for Chinese, Japanese, Russian, … And then someone else would come and say that the transliteration method we used is stupid, and we should totally use another method. And then we would end up becoming a Unicode → Latin transliterator with a blog engine attached.

No.

**Comment by felixfontein** [comment]
I wasn't talking about changing the current behavior. I was only talking about allowing to change behavior if needed and wanted. That's quite a huge difference. If we provide this infrastructure, anyone can provide a plugin for a specific language (via plugins.getnikola.com), and anyone who cares can install it, and anyone who wants no change does not have to install it.

And since when is "it might lead to some weird bugs here or there" a reason not to implement something new? I mean, as a little example, why did we introduce shortcodes? If someone used the syntax there in an existing blog, suddenly something is transformed which wasn't transformed before. Almost every change (except some simple fixes) risk changing behavior for an existing blog, resulting in such problems. So why should this be a reason to not implement this, out of these many changes?

**Comment by ralsina** [comment]
It's already possible, isn't it? You just need to monkeypatch slugify from a plugin that runs before the timeline is loaded.

**Comment by felixfontein** [comment]
No, except if your blog uses only one language or all languages it uses have the same rules.

(Passing through the language to `slugify` would allow to find a monkeypatch solution.)

**Comment by ralsina** [comment]
Adding the language is not horrible.

**Comment by Kwpolska** [comment]
Couldn’t you just get the language out of LocaleBorg anyways?

**Comment by felixfontein** [comment]
That doesn't work if you want to get the link to a page in another language than the current one (i.e. as soon as your blog has more than one language).

**Comment by Aeyoun** [comment]
Unicode normalization is starting to not sound like such a bad compromise after all.
