### ISSUE TITLE
Nikola bootstrap script

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola#2280]
And when I say 'bootstrap', I mean the verb that is much older than twitter.

Nikola is an end user application.  Pip and virtualenv are awesome tools, that developers (python developers only, if my experience in #python is any indication) know about and how to use.

Maybe we should come up with a way of creating a bootstrap script, like there is for pip with get-pip.py, that sets up a virtualenv and gets nikola installed into it without the user needing to know, or learn, python development tools.

**Comment by tritium21** [comment]
I have written a proof-of-concept https://github.com/tritium21/nikola_bootstrap

**Comment by Kwpolska** [comment]
This is an interesting idea. However, this involves quite a few issues:
* C extensions: lxml, Pillow, pyyaml (for watchdog) and some speedup packages (Mako, markupsafe, ?)
* pip and virtualenv are probably better off installed system-wide.
* It would be much nicer to allow customization of `nikola init` — I recommend defaulting to `-d` but making it configurable.
* Windows and Mac OS X users still need to figure out how to install Python 3. Windows users would need to install lxml wheels from Chris Gohlke’s site (which does not like robots), OS X users would need to install a C compiler.
* Linux users need to figure out what to install to get things to compile. We could provide some help and distro-based automation, but we can’t do it for every OS. And they need 1.5G+ of RAM to compile lxml, which will otherwise crash with a cryptic error message.
* We would still need a large troubleshooting guide, because there are so many things that can, and will, go wrong.

Note that we already have a [Dockerfile for Nikola](https://github.com/rbrewer123/docker_nikola) and a getting started guide on our website, that takes care of all this problems (which is down right now, @ralsina?)

**Comment by tritium21** [comment]
Asking *users* to install docker when I can point to *developers* who refuse to, is a non-starter.

* C extensions I can do nothing about other than try and notify users that they need to run an apt commend first.
* pip and virtualenv installed system wide by non-python developers will probably be ancient anyways, or not python-3
* I plan on changing it to allow more init customization.
* Pillow has wheels, lxml has a windows wheel if you don't mind using the previous version, markupsafe will would need visual c installed to get speedups, but it will work without them (I think I remember you saying windows is a second-class platform anyways for nikola).  But this is not the point.  The point is being able to tell end users "Use your system package manage, which you are already using, to install this set of package (python3, libxml2, ...), and then just run this script that takes care of all the unfamiliar parts"
* See previous
* Probably.

**Comment by tritium21** [comment]
Question for Mac users:

My understanding of the Mac ecosystem is very limited.  Does the way the average Mac user uses a python3 application make this script unnecessary for them?  Should this script, if it detects it is on a Mac, just print what commands to issue to homebrew and exit?  If so, what commands would they be?

**Comment by ralsina** [comment]
With pip 8.1 binary C-extension wheels for Linux work better, via https://github.com/pypa/manylinux

**Comment by Kwpolska** [comment]
@tritium21 A good starting place would be https://getnikola.com/getting-started.html → click on “Installing on OS X”. Hopefully, it works — but we need someone with a clean(-ish) Mac to test.

**Comment by tritium21** [comment]
@ralsina manylinux1 cannot be used with libxml, libxslt, or libjpeg.  So basically, the only hard c dependency (absolutely required for Nikola to run) that manylinux1 supports is zlib.

@Kwpolska I was actually hoping someone with a clean-ish mac would have recently installed Nikola.

**Comment by ralsina** [comment]
No action for over a year, closing. Anyone feel free to reopen if this idea is deemed worthwhile.
