### ISSUE TITLE
Create some repository of shortcodes

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2318]
So that gems like [the <audio> shortcode](https://gist.github.com/SpotlightKid/70f3ccdfacd9cfb091941a91f349924f) are not lost anywhere. This might even be a simple GitHub repo linked to on our pages.

Ideas, thoughts, recommendations?

cc @SpotlightKid

**Comment by SpotlightKid** [comment]
You *could* just add a `shortcodes` directory to the [plugins](https://github.com/getnikola/plugins) repository.

But since shortcodes will probably be mostly short, one-file affairs and are good for adding quick, site-specific features and rapid adaptions, I think it would be better to create a resource where Nikola users can add their shortcodes without a central moderation and keep updating them without the need for a PR, review, merging etc. You could still maintain a list of "officially approved" shortcodes (or just import them into the plugins repo).

Since AFAICS shortcodes templates can't be put into sub-directories of `shortcodes`, it is difficult to maintain them outside the main repository for your Nikola site (e.g. as a git submodule), so user's would have to copy them into their project anyway (and then can also easily adapt them to their needs).

**Comment by ralsina** [comment]
We could get shortcodes from gists, for example.

**Comment by Kwpolska** [comment]
For now, I added this shortcode to the manual.

**Comment by SpotlightKid** [comment]
How about adding a repository under the getnikola GH account with just a README.md file.

Shortcode authors could then just make a PR adding a link to their shortcode Gist or in another repository. that would give the Nikola some control over what's added as opposed to just setting up a wiki page.

The README could show some example shortcodes and detail the submission process and make some recommendations (or prescriptions) on how a shortcode should / needs to look like to be added.

I'd be willing to act as an editor for such a list.

**Comment by Kwpolska** [comment]
There, created https://github.com/getnikola/shortcodes. Please accept the organization invitation.
