### ISSUE TITLE
download directive

### ISSUE THREAD

**Issue by sindhus** [getnikola/nikola#2415]
hi, 

how do I link to a downloadable file?

i saw that on #770 that download directive is unimplemented, in the mean time is there a workaround so I can link to a file which is available in the `output/files/` dir (set it in `conf.py` using `FILES_FOLDER`)?

Something like this:

`.. file:: /files/myfile.f`

and a link to the file would lead it to be downloaded.

Thanks!

**Comment by ralsina** [comment]
What's the difference between that and just a regular link?

I don't recall a download directive at all, actually. There is a download
role that we could add for sphinx compatibility, but to be honest, I don't
understand what it does from reading the docs

http://www.sphinx-doc.org/en/stable/markup/inline.html#referencing-downloadable-files

**Comment by punchagan** [comment]
`FILES_FOLDERS` by default has the value `{'files': ''}`, which means `<nikola-site>/files/myfile.f` will get copied to the `output/myfile.f` folder.   And will be available at `<SITE_URL>/myfile.f`.

**Comment by punchagan** [comment]
@sindhus You can link to the file in your pages/posts using something like 

```rst
`My file </myfile.f>`__
```

**Comment by felixfontein** [comment]
My guess is that sindhus wants not to have to specify the path directly (i.e. when he changes `FILES_FOLDERS` the links should change as well), and/or wants to get error messages/warnings when the link targets don't exist in the `FILES_FOLDERS`. At least, that would be the main use cases for such a download directive I could think of. (I'd rather call it a files directive, though, since it is called `FILES_FOLDERS` and not `DOWNLOAD_FOLDERS`.)

**Comment by ralsina** [comment]
So. If anyone wants something like this, and cares to describe the behaviour, it's easy enough to implement.

**Comment by ralsina** [comment]
Noone did want it enough to describe it. Closing.
