### ISSUE TITLE
Integration with smartypants?

### ISSUE THREAD

**Issue by xuhdev** [getnikola/nikola#2453]
[smartypants](https://pythonhosted.org/smartypants/introduction.html) is a Python package which performs some operations to transform some ascii characters in HTML to a better looking version. For example, straight quotes (`" and "`) into “curly” quote HTML entities, Dashes (`--` and `---`) into en- and em-dash entities.

It looks to me that it is impossible to integrate it as a plugin. Do you have any ideas?

**Comment by felixfontein** [comment]
I guess you could run it as a filter, as it works with HTML output.

Out of curiosity: does it offer locale-dependent behavior, for example for smart quotes?

**Comment by Kwpolska** [comment]
The typogrify filter should already do that and more. It's English only,
but patching things to work for another language should be simple.

-- 
Chris Warrick <https://chriswarrick.com/>

On 19 Aug 2016 06:59, "Hong Xu" <notifications@github.com> wrote:

smartypants <https://pythonhosted.org/smartypants/introduction.html> is a
Python package which performs some operations to transform some ascii
characters in HTML to a better looking version. For example, straight
quotes (" and ") into “curly” quote HTML entities, Dashes (-- and ---) into
en- and em-dash entities.

It looks to me that it is impossible to integrate it as a plugin. Do you
have any ideas?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/getnikola/nikola/issues/2453>, or mute the thread

**Comment by xuhdev** [comment]
Hmm, didn't know typogrify before. Thanks!
