### ISSUE TITLE
Add an option to `nikola new_post` to create yyyy/mm/dd directory structures

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2513]
A lot of people want to have a `yyyy/mm/dd/slug` directory structure. So, let’s make it an option somewhere in `nikola new_post` (that can be also set as enabled by default in `conf.py`) to automatically create that directory tree for them.

Then there’s Jekyll-esque “replace dashes with slashes”, but that’s a story for another time.

**Comment by dubwhale** [comment]
If it could also allow custom URL structures that would be great. Currently have had to hack the post.py file in order to set the:

`self.folder = <my custom folder structure>`

I guess a conf format token string would work "Y/M/D" for your case, but relying purely on pre-defined tokens means if someone wants something that is possibel with tokens they cannot.

There any reason why a signal task couldn't be added 'folder_structure'?

**Comment by Kwpolska** [comment]
Uh, what do you mean? Do you know you can do something like `posts/something/or/other.rst` and end up with `output/posts/something/or/other/`? If that’s not it, please clarify.

**Comment by adarshdec23** [comment]
When you say `yyyy/mm/dd/slug`, does this mean `output/yyyy/mm/dd/slug` or `output/posts/yyyy/mm/dd/slug`?

**Comment by Kwpolska** [comment]
Depends on your POSTS config…
