### ISSUE TITLE
Can’t disable indexes while keeping RSS on

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2591]
In the new Taxonomy classes, one needs to keep indexes enabled if they want to have RSS enabled. That wasn’t necessary in the old scheme of things.

Also, disabling the index plugins without disabling RSS floods logs with `WARNING: Nikola: Unknown path request of kind: rss`.

**Comment by felixfontein** [comment]
I always found it strange that this was possible so far. I can of course add some special-case logic to allow to emulate this behavior, if you want that.

**Comment by Kwpolska** [comment]
I wouldn’t call it strange. The use-case is, of course, irclogs.getnikola.com. The indexes are pretty useless, because they contain all the posts (640 as of today), eat up disk space/CPU time when building, and there’s no point in reading all the logs like this. However, if someone wants to “follow” the IRC channel via RSS, that makes a little bit more sense.

But there are also other blogs, which disable the built-in indexes, replace it with simple post-lists (eg. one per section) and still want to have RSS.

Either way, that’s a case of <https://xkcd.com/1172/>.

**Comment by felixfontein** [comment]
Ok, there it does make sense.

For the other blogs, it might make more sense to tell the `classify_indexes` plugin to generate post lists instead of an index, so that there is a user-viewable analogoue to the RSS feed. (The current `classify_indexes` plugin doesn't allow this yet.)

You can also convert all indexes to post lists by modifying your theme's `index.tmpl` to behave like a post list and setting the posts per page counter to a large enough number.
