### ISSUE TITLE
Category sorting is not sufficient

### ISSUE THREAD

**Issue by kayhayen** [getnikola/nikola#2627]
Hello there,

I am using tags in "posts", to make my content easily browse able on http://speedcenter.nuitka.net/categories/index.html

With a "post", I am forced to give a date, presumably for ordering
purposes. I am currently using an old date, that I would even like
to be invisible. Or maybe I am going to use a reasonable one in
the future, e.g. the commit date of the test case. But it's going to
be the same one in a lot of cases if not always all cases.

The individual tags page is currently randomly sorted, listing the
cases in the RSS feed in arbitrary order, instead of sorting by name,
which would be better.

Is there a way, or any chance, you could add the slug or title as a
tie breaker when sorting posts with identical date? I presume this
must also affect 2 blog articles dated identically, order will be pseudo
random, file system order maybe?

Definitely not necessarily reproducible.

Thanks in advance,
Kay

**Comment by felixfontein** [comment]
Currently, posts are sorted first by priority (which doesn't do anything if you didn't define priorities manually), then by date, and then by `source_path` of the post. Since I cannot see from the generated pages what the source paths were: do you have any "random" ID/hash/... in the source paths which could cause this?

**Comment by felixfontein** [comment]
Oh: and which version of Nikola are you running?

**Comment by kayhayen** [comment]
This was 7.8.1, but soon will be 7.8.2 which I have read about. If you consider e.g. this link (might go away, due to renames of tags coming up): http://speedcenter.nuitka.net/categories/27_develop_steady.html

You can see that I am using the default slug, and it appears not sorted. Or do you mean with source_path, the file system path? They all live in "constructs/construct-TitleCasedName", no hashes are used in paths.

Yours,
Kay

**Comment by felixfontein** [comment]
Hmm, the sorting didn't change between 7.8.1 and 7.8.2, so 7.8.2 should have the same problem/bug. `source_path` is the path in the file system, so yeah, they should be sorted. I'll investigate that.

**Comment by felixfontein** [comment]
I can't reproduce this. Would it be possible for you to upload the source files somewhere? Please use `tar` or something else which preserves file system ordering of files and doesn't sort the filenames in a directory.

**Comment by kayhayen** [comment]
Here you go, this is a tar dump of my work directory, with "nuitka" and ".git" removed. It's not that huge. I am using ext4 file system in case that matters:

http://nuitka.net/volatile/issue_2627.tar.bz2

Running nikola with "build" and "deploy" is all I do in "update.py" which is my wrapper to create the RST files.

I somewhat merged my "conf.py" with default "conf.py" recently, but I didn't complete it. In my mind, it should not contain special stuff.

Yours,
Kay

Yours,
Kay

**Comment by felixfontein** [comment]
Thanks for the sources! Unfortunately, for me, the categories come out sorted.

(FYI: I removed almost all filters from the configuration except the `hackContentClasses` one. That shouldn't make a difference, though. And I didn't have `pygal` installed so I got no charts.)

Now I've looked in v7.8.1, and it turns out that the whole taxonomy-related code was rewritten since then (v7.8.1 was a bit older than I thought). In fact, it in v7.8.1, the posts per tags and categories weren't sorted with the same code as the timeline and others were (that was here: https://github.com/getnikola/nikola/blob/v7.8.1/nikola/nikola.py#L1981 and it is using the same sorting mechanism as in the current version).
Instead, the `render_tags` plugin did that manually here: https://github.com/getnikola/nikola/blob/v7.8.1/nikola/plugins/task/tags.py#L368 There you can see that it only cares about the date, and about nothing else.

So the result is that upgrading to v7.8.2 will fix the issue.

**Comment by felixfontein** [comment]
PR #2630 fixes a remaining problem: the category post lists are sorted, but in reversed order than one would expect. The PR should fix that (and make it easier to replace the sorting order in the future).

**Comment by felixfontein** [comment]
@kayhayen: if you use the current github master, you should get your posts in expected order.

**Comment by kayhayen** [comment]
I was updating to latest Nikola as first step to confirm that the original issue is fixed. The reverse order will be not nearly as annoying as unordered. I will however give master a shot later today.

**Comment by felixfontein** [comment]
How that there's v7.8.3, you can simply use that instead of switching to github master.

**Comment by kayhayen** [comment]
I can confirm that 7.8.2 did do away with random sorting indeed, and that 7.8.3 sorts in the right order. Thanks a lot.

**Comment by felixfontein** [comment]
Good to hear!
