### ISSUE TITLE
Update documentation to put "create website" on par with "create blog"

### ISSUE THREAD

**Issue by mckea** [getnikola/nikola#2642]
Currently (or at least the last time I consulted the docs) the Nikola documentation assumes the user will create a blog, and then, elsewhere, describes in sparse detail how one would go about modifying that process to create a website instead.

Creating a website instead of a blog seems like a common enough use case to warrant a promotion in how it is handled in the documentation.  Perhaps separate "Creating a blog - start here" and "Creating a website - start here" links.

**Comment by Kwpolska** [comment]
Writing and maintaining two separate documents makes no sense — a lot of the information would be duplicated, especially since most things that apply to blog posts also applies to static pages. The default Nikola setup assumes blogs, and so the extra work needed applies to people who do not want blogs.

I added links to the [not a blog](https://getnikola.com/creating-a-site-not-a-blog-with-nikola.html) guide to Getting Started and the Handbook. If you can propose something better, that does not increase maintenance burden, we’d love to hear about your ideas.
