### ISSUE TITLE
Webiso date_format should always ask Python

### ISSUE THREAD

**Issue by sukiletxe** [getnikola/nikola#2662]
Currently, the date format handlers are asked no matter whichdate_format is passed to them, including webiso. This could lead to the `time` element to have the wrong `datetime` value.

**Comment by Kwpolska** [comment]
Uh, what?

**Comment by felixfontein** [comment]
@sukiletxe: That only happens if you have a date format handler which handles `webiso` incorrectly. That would be a bug in the date format handler.

We could of course also always use Nikola code when `webiso` is requested.

@Kwpolska: he is referring to the code around here: https://github.com/getnikola/nikola/blob/master/nikola/utils.py#L1234

**Comment by sukiletxe** [comment]
@felixfontein: I know, but isn't that a behaviour that should be taken into account? Imho, webiso is a Nikola-specific date format, whose output should always be the default one.

**Comment by felixfontein** [comment]
I don't really care too much :) Feel free to make a PR which changes this, i.e. which only asks the date format handlers when the format isn't `webiso`.
