### ISSUE TITLE
ENABLE_AUTHOR_PAGES sould create indexes with only one author

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2728]
Currently, if you start a blog with only one author and set ENABLE_AUTHOR_PAGES, it will add links to author pages but not actually generate them, thus creating broken links.

Possible solutions are:

1. Create the links only if there is more than one author
2. Create the author pages even if there is only one author

Since 1. implies touching templates in all themes, and 2. implies deleting 2 lines, I am proposing the 2nd.

Looks like I created this bug in my own theme somehow. Closing

**Comment by Kwpolska** [comment]
How hacky would it be to return the global archive link in this case? (Might require dependency shenanigans)

**Comment by felixfontein** [comment]
I guess the main problems are dependency related: if you add a new post with another author, there probably won't be a rebuild of the existing pages using that link. (I guess that's what you mean with dependency shenanigans.)

One solution would be to embed the link into the page's dependencies, though that would trigger rebuilds of all existing pages so far in existing blogs.

**Comment by Kwpolska** [comment]
Triggering rebuilds is not a problem. Users can expect all pages to be
rebuilt when they upgrade, and I already changed the global context twice
in the past few days.


-- 
Chris Warrick <https://chriswarrick.com/>

On 19 Apr 2017 9:21 p.m., "Felix Fontein" <notifications@github.com> wrote:

I guess the main problems are dependency related: if you add a new post
with another author, there probably won't be a rebuild of the existing
pages using that link. (I guess that's what you mean with dependency
shenanigans.)

One solution would be to embed the link into the page's dependencies,
though that would trigger rebuilds of all existing pages so far in existing
blogs.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/getnikola/nikola/issues/2728#issuecomment-295400436>,
or mute the thread

**Comment by felixfontein** [comment]
Ok. Then the author plugin should add the links as dependencies to the post objects, I'd say. Then in case someone disables the author plugin, it won't break.

**Comment by felixfontein** [comment]
Actually, I just started implementing this, and noticed that the `authors` plugin is already putting a boolean `author_pages_generated` into the global context, whose value determines whether author pages are generated or not. So in case this changes, *everything* is already being rebuilt.

With that being the case, I'm wondering whether we should really return the global archive link in case author pages are not created, since that situation is already easy to handle in templates (and if you do it wrong, it's your bug). What do you think?

**Comment by ralsina** [comment]
Not really sure. I just ended up using the author_pages_generated
conditional.

**Comment by Kwpolska** [comment]
Let's not change this then. Leaving it up to theme authors is easier, and
we already do that in built-in themes.

-- 
Chris Warrick <https://chriswarrick.com/>
