### ISSUE TITLE
Make compilers use new UUID-based shortcode API

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2752]
The new API is better. So, we should port the compilers to it.

Included

* [x] html
* [x] ipynb
* [x] markdown
* [ ] ~~pandoc~~ too complicated because of the multiple outputs
* [ ] ~~php~~ I am not doing this
* [x] rest

Plugins: v8 only, v7 is frozen.

* [x] asciidoc
* [x] bbcode
* [x] commonmark
* [x] kramdown (in plugins/ PR)
* [ ] latex (has no v8 version)
* [x] ~~markmin~~ obscure and apparently py2-only
* [x] mediawiki
* [x] misaka
* [x] mistune
* [ ] ~~odt~~ not worth the effort
* [ ] orgmode
* [ ] rest_html5 (has no v8 version)
* [x] textile
* [ ] ~~txt2tags~~ is py2 only, and v8 is py3 only so, nope.
* [ ] ~~wiki~~ The underlying library is broken, and nobody uses this
* [ ] ~~wordpress~~

**Comment by felixfontein** [comment]
The WordPress compiler doesn't support Nikola shortcodes, it has its own WordPress-like shortcode system. I don't think it makes sense to include Nikola shortcodes into the WordPress compiler, since it was never thought to be used for new posts, but for processing posts of converted blogs. And adding support now will only break things, in case someone used `{{` ... `}}` in a WordPress post.

**Comment by ralsina** [comment]
Sounds good to me, let's cross it.

**Comment by ralsina** [comment]
The PHP plugin doesn't seem to support shortcodes and the pandoc plugin is weird.

**Comment by ralsina** [comment]
Ok, I made a huuuuuge mess of things trying to do this.

I was working on the v7 plugins using master to test, and then things get messy.

I will have to test everything with v7 and see how it works.

**Comment by ralsina** [comment]
did a hard reset on today's work, and will try to do it better now.

**Comment by ralsina** [comment]
Annnnd I had done the same thing with asciidoc before. ARGGGGGH

**Comment by Kwpolska** [comment]
Seems to be (mostly) done.
