### ISSUE TITLE
What’s up with archive feeds?

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2783]
We have path handlers for `archive_atom` and `archive_rss`, but there is also `always_disable_rss = True` and `generate_atom_feeds_for_post_lists = False`. Perhaps those path handlers are wrong and we should make them `False`? (cc @felixfontein)

**Comment by felixfontein** [comment]
`generate_atom_feeds_for_post_lists = False` only applies to post lists (as opposed to indexes). So Atom feeds are generated only if you have indexes as archives.

That RSS feeds are disabled is probably because no-one wants to use a feedreader for archives (as opposed to tags, categories, sections, ...).

What do you mean by that the path handlers should be `False`?

**Comment by Kwpolska** [comment]
Taxonomy path handlers are disabled by the means of a `False` value for its docstring in `path_handler_docstrings`.

I did that for archive_rss, and added a note to archive_atom about the index requirement.

**Comment by felixfontein** [comment]
Ah, ok. Thanks!

**Comment by Kwpolska** [comment]
One more thing, why is there no `/2017/index.atom` even though `/2017/05/index.atom` is generated?

**Comment by felixfontein** [comment]
Maybe `2017/index.html` is a list of months and not a list of posts in that year? That would explain why no Atom feed is there. For my blogs, Atom feeds are there at all levels.
