### ISSUE TITLE
metadata in JSON/YAML/TOML format

### ISSUE THREAD

**Issue by hieu-n** [getnikola/nikola#2800]
Hi,

I'm coming from Hugo - Static Site Generator. With Hugo, it's possible to use define metadata in different formats (json/yaml/toml): https://gohugo.io/content/front-matter/

Does Nikola also do that? I had a look Nikola Handbook and apparently the only format for metadata is reStructuredText. 

Basically, what I am trying to do is to automatically generate posts with custom metadata fields. So, I expect converting python dicts to metadata in json/yaml format would be easier than to reStructuredText format (which I am not familiar with).

Hieu

**Comment by Kwpolska** [comment]
Nikola’s metadata isn’t really reStructuredText; it’s just HTML comments that look kinda like reST syntax:

    .. key: value

where `key` and `value` are strings. If you’re fine with only strings as data, then outputting in that format is trivial. Otherwise, you can use [data files](https://getnikola.com/handbook.html#the-global-context-and-data-files) which support JSON/YAML/TOML files.

**Comment by ralsina** [comment]
OTOH, I regret that choice a lot. So, let's make YAML/TOML metadata work.
