### ISSUE TITLE
conf.py has too many features

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2840]
(Those are only some propositions and examples. If someone disagrees with my opinions, or wants some other features gone, feel free to comment.)

### Unnecessary customization

- [ ] `TRANSLATIONS_PATTERN` — this is useful for backwards compatibility with multilingual sites created with Nikola v6 or older. Perhaps we could just offer some auto-upgrade and cut some code?
- [ ] `TAGLIST_MINIMUM_POSTS`
- [x] `FEED_PREVIEWIMAGE` — how many people don’t want this?
- [x] `USE_OPEN_GRAPH` — how many people don’t want this?
- [x] `SITEMAP_INCLUDE_FILELESS_DIRS` — how many people care?
- [ ] `INDEX_FILE` — how many people don’t want 'index.html'?

### Unneeded features

- [x] `USE_BASE_TAG` — this feature never helped anyone, is a quirk of the HTML spec, and has tripped some people (you must use nikola serve, or a httpd, and if you want multiple domain names, you need to disable that feature anyway)
- [ ] `SOCIAL_BUTTONS_CODE` — can also be done with `BODY_END`
- [ ] `LICENSE` — can be done inside `CONTENT_FOOTER` proper

### Split out to plugins?

- [ ] `DATE_FANCINESS`
- [ ] `WRITE_TAG_CLOUD`
- [x] `LESS_COMPILER`/`LESS_OPTIONS`/`SASS_COMPILER`/`SASS_OPTIONS` — those are already plugins but their options are still in conf.py
- [ ] `HYPHENATE` (→ filter?)
- [ ] `FILE_METADATA_REGEXP` / `FILE_METADATA_UNSLUGIFY_TITLES`

**Others:** We should rethink filter configuration.

**Comment by felixfontein** [comment]
`TAGLIST_MINIMUM_POSTS`: I'm voting for keeping that. As soon as your blog gets bigger, it's really nice to restrict your tag list to tags with a certain minimum number of posts. Otherwise, your tag list is just way too long.

`FEED_PREVIEWIMAGE`: The only thing this is doing is disabling preview images (when set to `False`) if `previewimage` is in the metadata, right? So if you don't want preview images, don't add `previewimage` metadata fields. So for me, there's no reason to keep `FEED_PREVIEWIMAGE`.

`USE_OPEN_GRAPH`: I guess I don't care since I have my own theme without it anyway ;-)

`INDEX_FILE`: I guess you still need it if you want `index.php` instead of `index.html`. Though it is kind of tricky, since `index` or `.html` is hardcoded at several places into Nikola, so you might end up with `index.html` even if you defined `INDEX_FILE` differently. So we should either properly fix this, so you can really control file name generation better, or we drop `INDEX_FILE` and force everyone to stick to `index.html`.

`LICENSE`: I don't use this, but I like the idea of making it easy for people to specify licenses.

**Comment by Kwpolska** [comment]
All LICENSE is used for is text substitution within CONTENT_FOOTER.

**Comment by felixfontein** [comment]
True. It's still kind of nice to have it, just to remind people that blogs can have a license, too. I won't complain if it is removed, though; I guess it's also OK if we extend the comment for `CONTENT_FOOTER` so that people are reminded there that they can add a license.

**Comment by tritium21** [comment]
`INDEX_FILE` has a use case if you are, for example, using an old IIS instance to serve your site, and you dont have rights to configure it - IIS defaults to `default.htm(l)` instead of `index.html`.  (recent versions of IIS default to `index.htm(l)` and `default.htm(l)`).  It should still be configurable, but it doesn't need to live in the default config.

**Comment by ralsina** [comment]
Extra bous points for it being ".htm" when that limitation in the filesystem has not been there for 23 years.

**Comment by tritium21** [comment]
That limitation hasn't ever existed for any OS that could run IIS (NT), yet, `.htm` - MS is obsessive about backwards compatibility, including offering an `8.3` interface to the filesystem *even on Windows 10*.  But this is a tangent.

**Comment by Kwpolska** [comment]
I guess we’re good enough for now.
