### ISSUE TITLE
Can nikola handle a large site with more than 150,000 post files?

### ISSUE THREAD

**Issue by hieu-n** [getnikola/nikola#2842]
Hi,

I have tried a few static site generators (SSGs). One common problem I often encountered was the SSG loads all the posts into memory to work with. Some like Hugo also uses up all the CPU and makes my PC unusable during its building process. 

Before converting my hundred thousand posts to nikola format, I would like to know how nikola would handle a large number of post files.

**Comment by felixfontein** [comment]
That's a good question! :) I'm not sure whether anyone tried that yet. I *think* Nikola doesn't read all files into memory at once, it only stores all metadata in memory. So it might be kind of usable.

Nikola will use only one core by default. You can tell [doit](http://pydoit.org) (Nikola is based on it) to use multiprocessing for using multiple cores; I'm not sure whether this is a good idea in this situation, though, because it will use much more memory. Multithreading should not have that problem, but since there's no proper multithreading in Python this might not give you much speedup.

In case you try Nikola, you should try to configure doit to use a proper database as the [backend](http://pydoit.org/cmd_run.html#db-backend). Writing everything into a file which is loaded at startup and dumped at shutdown doesn't sound like a good idea with such a huge amount of data :)
(I don't know if anybody ever tried that yet. Maybe @schettino72 knows?)

Also, some of the recent changes by @ralsina should allow you to recycle many parts of the Hugo version of your site, so you should be able to try Nikol without converting the posts. See https://getnikola.com/handbook.html#metadata-formats and https://getnikola.com/handbook.html#mapping-metadata-from-other-formats for some information.

**Comment by punchagan** [comment]
This is indeed a fun question to try and answer.  

I went ahead and [created a test blog](https://gist.github.com/65fe1428e9b4314e22b4775c8dde2089) with 150k random posts. 

The size of the `posts/` directory was about 600M on disk. 

``` bash
$ du -hs posts/
609M    posts/
```

> I think Nikola doesn't read all files into memory at once, it only stores all metadata in memory. So it might be kind of usable.

I would've thought that this would be the case, but by the end of the first `nikola build`, the total memory being used was 12.3G! 

> Nikola will use only one core by default.

I did use the default setting, and only one core was used. It took me about an hour to have the build for the whole site. 

```
real    64m27.359s
user    60m32.327s
sys     1m45.773s 
```

To test if the site is usable on incremental builds, I added a single post after building the site once and ran a build again. 

An incremental build didn't turn out to be any less of a memory hog, either.  It again needed the `12.3G` of memory.  It took about half the time of a full build to run. :cry: 

```
real    32m15.617s
user    31m56.919s
sys     0m20.326s
```

In it's current state, it doesn't look like using Nikola to manage such a huge site would be a pleasant experience. 

PS: For all these tests, I used a machine with an SSD. I was running `Nikola v7.8.8` on `Python 3.4.3`.

**Comment by felixfontein** [comment]
About the memory: since Python uses garbage collection, you can end up having everything in memory even though Nikola is not explicitly storing all posts in memory, because there's just more memory around so there's no need to clean up. This could probably be tested better if you explicitly force Python to use at most 2 GB of RAM or so. No idea how to do that though :)

Out of curiosity: which OS are you using? (OSX or Linux?)

**Comment by punchagan** [comment]
I'm using Linux.  I think the posts are being read into memory during dependency calculation, and I'm not sure just fixing the limit for memory would help. 

For a test blog with 5k posts, building the site for the first time requires about 830M. Rebuilding the site without any changes, requires about 800M and running `nikola reset-dep` also seems to require about the same amount of memory.  I wonder if there's a way to tell `doit` to not do any dependency calculations and just run all the tasks.

**Comment by felixfontein** [comment]
But are the posts *kept* in memory by dependency calculation, or do they just happen to stay there because the garbage collector is too lazy and there's still a lot of memory available?

Regarding doig executing all tasks, simply specify `-a`: `nikola build -a` (see `nikola help build`).

**Comment by schettino72** [comment]
Thanks all for the interest :)

@punchagan could you  include a no-op test to compare the time?

I dont expect doit to be able to handle this large site without some tweaks. If possible to make it acceptable i am not sure... I am not that familiar about Nikola code so what I talk applies only to doit.

### Memory usage

By default doit check file MD5 to compare if there was any change. Not sure how/when python garbage collector comes into play. One thing that you could do is to use only timestamp to compare files. This is already available in doit. see option `--check-file-uptodate` [1] This was implemented by a guy who had file dependencies of several GB, not sure how well the speed gain will be for a large amount of files.

Of course this is trade-off. I remember reading about how Facebook implemented a process that watches for file changes to use Mercurial on large repository. So when you run `hg status` it would not check all files but already have this information available. 


### Dependency tree

The next most time consuming of `doit` itself is building the dependency tree. That ends up being built even if no task is execute. Once I implemented something to mitigate that but it was kind of specific to the problem domain [2].

### Task creation

My last suggestion would be to directly create `Task` objects. `doit` main interface you pass dictionaries that goes through quite a few error checking before creating a task. I **guess** that creating tasks directly could improve that significantly.

### __slots__

Once I experimented adding __slots__ to the `Task`, the results were not relevant (at least for my example), but it should also help with memory footprint.

[1] http://pydoit.org/cmd_run.html?highlight=check_file_uptodate#check-file-uptodate. this 
[2] https://schettino72.wordpress.com/2011/07/19/faster-scons-on-top-of-doit/

**Comment by punchagan** [comment]
> But are the posts kept in memory by dependency calculation, or do they just happen to stay there because the garbage collector is too lazy and there's still a lot of memory available?

I'm not aware of the exact scheduling algorithm for the garbage collector, but I'm pretty sure it doesn't stay dormant for so long.  To test this, I added a [print callback that gets called everytime a gc is started or stopped](https://docs.python.org/3/library/gc.html#gc.callbacks), and surely the garbage collection happens numerous times while building a site. 

So, I don't think this is really a garbage collection problem.

**Comment by punchagan** [comment]
> @punchagan could you include a no-op test to compare the time?

I updated the [comment above](https://github.com/getnikola/nikola/issues/2842#issuecomment-308344745) to add timing for a no-op build.

**Comment by felixfontein** [comment]
I've created a site with 5001 posts with @punchagan's script, and did some debugging with objgraph to see where a lot of objects are generated. (For me, Nikola needed around ~500 MB of memory.) I analyzed a no-op `nikola build`.

Out of all task generating plugins, the following generated a particularly huge number of objects:

Scanning posts (only calling `PostScanner` plugins):
```
defaultdict                   30067    +30007
function                      34507    +20022
cell                          16343    +15004
dict                          18885    +10013
list                          15193    +10012
tuple                         20805    +10012
Functionary                   10003    +10002
set                            6061     +5001
method                         6792     +5001
Post                           5001     +5001
```

`RenderPosts` plugin task generation:
```
list              90654    +74885
tuple             70818    +49860
dict              38936    +20007
function          49512    +15003
config_changed    10003    +10003
cell              26344     +9995
set               16067     +9852
Task               5003     +5003
method            11793     +5000
```

`RenderPages` plugin task generation:
```
list               190854   +100037
dict                74043    +35026
tuple              105862    +35007
function            64620    +15033
cell                41352    +15003
config_changed      25010    +15003
set                 26083    +10004
Task                10011     +5002
method              16798     +5001
```

`Sources` plugin task generation:
```
list             236582    +45020
tuple            120996    +15003
dict              84280    +10004
set               36181    +10004
Task              15060     +5002
function          69666     +5001
cell              46399     +5001
config_changed    30054     +5001
```

`RenderTaxonomies` plugin task generation:
```
list               336226    +99638
tuple              214533    +93537
dict               177594    +93313
function           115933    +46267
cell                92626    +46226
config_changed      76280    +46226
set                 37773     +1590
Task                15853      +792
method              17449      +651
```

I don't think the posts themselves are kept anywhere in memory. I guess most of the memory is taken by structures describing the tasks to be performed.

**Comment by stefanos82** [comment]
OK, this discussion gave me goosebumps, because last night I was studying more about Cython and the first thing that came in my mind was how could Cython benefit Nikola's compilation performance at its most critical parts.

I planned to ask @ralsina again about how he run his test a while ago we discussed this topic via IRC, but this topic covered me.

Now I got more intrigued to see Cython in use. I use Nikola myself and I would love to see a competing performance of that of Hugo.

**Comment by ralsina** [comment]
Some things can be made faster. You may notice Hugo supports the faster
thing each time:

* Post compiling can be faster. Using misaka or mistune+cython is 4x faster
than using reSt.
* Template rendering can be faster. I suspect go templates are faster than
Jinja/Mako
* Dependency checking gets complicated enough with enough tasks that it
overwhelms everything else!

I suspect task dependencies are O(n^2) so once the number of tasks gets
huge enough it may actually be cheaper to just REBUILD EVERYTHING.

I have played with reimplementing a small subset of doit's functionality as
a go package. It seems I can schedule/sort 10K tasks in ~5 seconds. But it
is indeed quadratic (maybe because I suck as a developer ;-) and 20K take
20s, 40K take 80s, 80K take 320s, and 160K would probably take 16 minutes
**just to sort them and check if they are up to date**

And the number of tasks a 150K-post site would create is maybe 1 million or
so?

Right now, it's just not worth it to even think that big. Will it work?
Sure, just throw enough hardware at it and it will. Will it be fast and
light? Nope. How do we fix it? No idea. We *can* try to make "reasonable"
workloads work much faster. We *can* create suggestions for things that
will work better for massive sites.

**Comment by stefanos82** [comment]
@ralsina I have tried @punchagan's script and decided to give it a go. I have tried to build it with `nikola build --process=4 --parallel-type=thread`, as also with `nikola build --process=4` commands, but for some reason Nikola insist on using a single core from my CPU which is a 4-core i5 CPU.

Is this behavior normal? I'm using the latest version on a virtual environment with Python 3.6.1 on a Debian testing 64-bit system.

**Comment by ralsina** [comment]
No, not normal. I don't know if the threading model does much, considering
all the issues in python about threads, but the multiprocess one should
work.

**Comment by stefanos82** [comment]
It does not I'm afraid :( it took a while to scan the whole demo and while was doing so, it was using a single core and still does actually as it still hasn't finished yet.

**Comment by schettino72** [comment]
@stefanos82 the parallel is for task execution. **Loading** tasks is never parallel.

**Comment by stefanos82** [comment]
@schettino72 ah I see, I didn't know that. Any reason why it consumes all of my RAM? My system it's almost unable to function due to 8GB consumption.

Is there a way to limit the memory usage?

**Comment by schettino72** [comment]
I am not sure about the average task size. How many tasks are you creating? 600,000 ? 15KB per task?

No, currently there is no way to limit memory usage or get rid of tasks before the process finishes.
Without changes in *doit* your only hope would be to create tasks only if needed...

I would tackle the problem in a different way... trying to work with less tasks. 
Can the build process be broken down into different sections: by year, or by folder, or by stages?

i.e. doit supports creation of tasks dynamically. Create a single task that checks if there any changes in a folder, if no changes dont even create tasks and save a lot of memory and time.

I have never looked at optimizing memory consumption in doit, so it probably can be improved a lot.

**Comment by stefanos82** [comment]
@schettino72 basically I replicated @punchagan's steps from [test_big_blog.py](https://gist.github.com/65fe1428e9b4314e22b4775c8dde2089), which basically tells you to initialize an empty nikola project, then run the script to generate around 150K posts and then run `nikola build`.

Those were my steps to be honest with you.

One thing that caught my attention is the heaviness of doit processing. I wonder how it could perform with some async mechanism, either like a modern approach with Python 3.5 `async / await` support or with some `yield from` with <= `3.4` support.

**Comment by gour** [comment]
@ralsina 

> Post compiling can be faster. Using misaka or mistune+cython is 4x faster than using reSt.

What do you think about e.g. using Asciidoctor which is, at least for Asciidoc markup ~20x faster than using python version?

**Comment by Kwpolska** [comment]
AsciiDoc is a terrible markup format, and forking thousands of processes is really expensive.

**Comment by gour** [comment]
For the sake of comparison with the test mentioned in Hugo [docs](http://gohugo.io/overview/introduction/l) I have used the above script to generate 5k rst & Asciidoc posts...

Here are results for rst markup:

- initial build 
        ```123.52user 6.79system 2:17.25elapsed 94%CPU (0avgtext+0avgdata 482356maxresident)k
        4096inputs+335296outputs (245major+193842minor)pagefaults 0swaps
        ```
- incremental build
       ```36.22user 1.54system 0:39.45elapsed 95%CPU (0avgtext+0avgdata 553208maxresident)k
      0inputs+11000outputs (13major+152009minor)pagefaults 0swaps
       ```

and same for 5k posts using Asciidoc markup processed with Asciidoctor:

- initial build
       ```578.19user 90.86system 11:27.30elapsed 97%CPU (0avgtext+0avgdata 453432maxresident)k
       7088inputs+375560outputs (221major+15933766minor)pagefaults 0swaps
       ```

- incremental build
        ```37.12user 1.62system 0:39.99elapsed 96%CPU (0avgtext+0avgdata 548040maxresident)k
        0inputs+10808outputs (0major+227674minor)pagefaults 0swaps
        ```

which shows that even for the sites in the 5k-posts range, rst is recommended markup (I did not play with markdown which is certainly too simple markup for my own usage.) to be used with Nikola.

**Comment by ralsina** [comment]
So, "probably not".

Closing.
