### ISSUE TITLE
inconsistent handling of Tag strings

### ISSUE THREAD

**Issue by charlesay** [getnikola/nikola#2934]
### Environment

**Python Version: *3.6.3-1*

**Nikola Version:7.8.10-5 (as provided by https://aur.archlinux.org/packages/nikola/) **

**Operating System: Arch Linux**

### Description:
When a tag in a post contains spaces the space is converted to a dash in the url of the page for the tag, as also happens in titles and slugs.

But when one puts the same string for the tag in a special path handler link of the format ` <link://tag/''>`_, the link that generates just omits the space (so the link is broken).

An Example:
the tag: ,FC Union Berlin,
the link in the tag page: http://0.0.0.0:8000/categories/fc-union-berlin/
the link as i would naively put it: `FC Union Berlin <link://tag/'FC Union Berlin'>`_
and the link that produces: http://0.0.0.0:8000/categories/fcunionberlin/
... which leads to a 404.

Similar issues arise from special characters like ä, which are converted to for example 'a' in the actual urls, but  to 'c3a4' in the link.

See also Tritiums remarks on irc (https://irclogs.getnikola.com/logs/2017-12-12/)

**Comment by Kwpolska** [comment]
Sorry for taking so long to look at this.

Good news: this is fixed in `master`. Bad news: the fix won’t work for reStructuredText, which mangles the URLs (removes spaces) before Nikola gets them. I’m afraid you’ll have to use the slugified URL in your `link://` tags in reST (accents work fine though).
