### ISSUE TITLE
Just something that took me a while to figure out

### ISSUE THREAD

**Issue by assarbad** [getnikola/nikola#2941]
I was using a `pyenv` to install Python 3.6.4 and in order to install Nikola in it, using the `pip` method I needed to install the following packages: `build-essential libbz2-dev libsqlite3-dev libreadline-dev libxml2-dev libjpeg-dev libxslt-dev`.

That was on Ubuntu 14.04.5 (ARM).

Since the `pip` output was somewhat misleading and it took me a considerable time to figure it out, I thought I'd open a ticket here so others can find the info.

NB: `libbz2-dev libsqlite3-dev libreadline-dev ` were mostly required to have a feature-complete Python 3.6.4 ... the remainder was needed to build binary Python extensions.

**Comment by tritium21** [comment]
What do you intend to accomplish here?

If you are using pyenv, you are in python power user territory.  I think building python and pillow, and lxml is out of scope for nikola documentation, since most users wont be on arm, build python, or have to build lxml or pillow (they have manylinux - x86-64 generic - wheels)

**Comment by Kwpolska** [comment]
We used to list the packages in our [Getting Started](https://getnikola.com/getting-started.html) guide, but I removed that due to manylinux1 wheels (most people are on x86_64 so they can use them). That said, there still are some generic instructions:

> * If you are getting errors about missing Python.h, you need to install development packages for Python (eg. python3-dev or python3-devel).
> * Install libxml2, libxslt, zlib and their development headers.
> * Use your package manager’s option to install build dependencies for their lxml and Pillow packages.

And as @tritium21 said, `pyenv` is an advanced technique, Nikola is compatible with Python 3.4 which is in 14.04 repositories.

**Comment by assarbad** [comment]
Yeah folks, I was just trying to help future internauts who may have come across the same issue. I didn't really expect _any_ action other than that this ticket would be closed, since the purpose was just sharing what I had found out.
