### ISSUE TITLE
Installation procedure can be much clearer

### ISSUE THREAD

**Issue by stitch** [getnikola/nikola#2953]
Hi Nikola team,

My initial experience with Nikola have not been positive. To improve the quality of the project, i've tried to summarize my experiences, in the hope this would become easier to use and faster to adopt for novices and advanced users alike.

1: The installation procedure for this project is not fit for beginning users. It misses a step in making it very explicit that you should create the content of your project _OUTSIDE_ the virtual environment. It should be somehow clear that a virtual environment is disposable / rebuildable and in itself holds no value. At the same time the content is unique and special: it holds value as it cannot be easily recreated. Step 1 and 2 deliver a project inside the virtual environment, which makes no sense. There should perhaps be some directory traversing. (Also for Git users, uploading your whole virtual environment is not efficient at all).

2: The small box on the right side of the getting started page (with a series of commands) is a terrible abstraction: it is some sort of a decision tree a new user has to walk through. If you support multiple operating systems, make sure the whole procedure is listed in the installation guide for that operating system so the user doesn't have to think about it. What happens currently is that some text is "normalized" into a separate section, where in the normalization contains an "if" statement which cancels out the normalization. Just duplicate some parts of the manual so all instructions for installation could be copy-pasted and be of no further concern for a user. If you deduplicate, all and any steps are the same for all operating systems and there are no deviations. Otherwise, don't deduplicate.

3: The virtual environment commands might be abstracted away: having a choice depending on OS is not a great way to use Nikola on different platforms. Given it's somewhat trivial to determine the platform you're on etc, choosing the right virtualenv is trivial inside a script. Why would that burden be passed to an end user?

4: It is unclear how to continue working on a project when you've closed the virtual environment. As this is the most used functionality, it might be part of the "getting started", before the "next steps". Continuing to working on a project is currently a pretty big hurdle because it's not explicitly told what to do. Using commands like "source bin/activate" is not a natural thing to do for a novice. In what directory should that happen etc?... Some guidance would let novices continue their work with ease.

5: Case sensitivity (pedantry): is the project/tool called Nikola or nikola? The install page shows both, where it starts with "Nikola[extras]" first. It implies that you type things starting with a capital letter, including the Help command, which is then found wrong and a suggestion of "help" is offered. Just make a choice.

Regards,
Elger / Stitch

**Comment by stitch** [comment]
Some additional notes:

6: After moving the virtualenv separate of my content, it seems that the sample content needs mako templates to be at a certain location (absolute location). This seems strange: why is this project or the example content mixing the working environment with a project or vice versa? Nikola should be intelligent enough to know where it and it's dependencies are installed, or the files have an explicit requirement in (the sample) project and should not be part of the virtual environment.

FileNotFoundError: [Errno 2] No such file or directory: '/Applications/XAMPP/xamppfiles/htdocs/museuminfo/nikola/lib/python3.6/site-packages/nikola/data/shortcodes/mako/raw.tmpl'

While Nicola is currently installed in 
(nikola) macbook AwesomeSpace $ which nikola
/Applications/XAMPP/xamppfiles/htdocs/nikola/bin/nikola

Also errors on Unknown gallery: demo.

This is based on the sample project as instructed in the installation manual, which might assume some things which assumes Nikola is installed somewhere where it is not. As said in point 1: Please make a strong separation between a worthless virtual environment and the valuable content.

7: It should also be added how to "exit" the virtual environment. As "exit" just closes the shell, which is really annoying. It doesn't even go back to the before-virtual-environment situation.

**Comment by ralsina** [comment]
Thanks for the feedback. Some comments, explanations on why things are the way they are coming up.

1. Sure, we should say that you should not put the site inside the virtualenv. 

2. All the commands in the right side work in both linux, windows, and OSX AFAIK, except for the 1st one about setting up virtualenv. So, your suggestion is to create 3 or 4 separate guides with the 1st paragraph being different? 

3. I don't understand what you say.

4. It should be done exactly as shown in the same getting started guide, the exact same way you did it before. But sure, it can be described better, I will take a shot at it.

5. Platform conventions. The project is called Nikola, uppercase initial because it's a proper name. But commands are supposed to be lowercase. Nowhere in any of the examples is anything written in uppercase other than in the name of the project. Anyway, we *could* write that in lowercase too, since it works. I'll think about it.

6. Python packages cannot be moved around.

**Comment by Kwpolska** [comment]
I do agree that the guide might be reorganized (perhaps with some OS choice, akin to old GitHub guides?). But note that we can’t also write a large guide that explains virtualenvs, for example, since the focus is getting Nikola installed. And please do remember that writing documentation is never easy — what is easy for one person is hard for another. Something a programmer understands well might be troublesome for non-programmers. And things you’ve been doing for years on end tend to look simpler to you than they are in reality.

**Comment by ralsina** [comment]
Unless @Kwpolska objects let's close this issue.

Yes, every piece of documentation we have could be improved. I don't think it makes sense to have open issues for each one.

**Comment by Kwpolska** [comment]
I’ve modified the instructions a little bit now. I had already switched it to the saner `python3 -m venv` command 2 months ago, and now I split it into *nix and Windows sections, so it should be clearer.

**Comment by ralsina** [comment]
@Kwpolska nice!
