### ISSUE TITLE
should keywords be treated as string (for smartjoin)

### ISSUE THREAD

**Issue by tbm** [getnikola/nikola#3080]
**Nikola Version:** 8.0.0beta1

I get the following:
```
    callable_(context, *args, **kwargs)
  File "/home/tbm/homepage/cache/.mako.tmp/base.tmpl.py", line 73, in render_body
    context['self'].extra_head(**pageargs)
  File "/home/tbm/homepage/cache/.mako.tmp/post.tmpl.py", line 164, in render_extra_head
    __M_writer(filters.html_escape(str(smartjoin(', ', post.meta('keywords')))))
  File "/home/tbm/.local/lib/python3.5/site-packages/nikola/utils.py", line 1884, in smartjoin
    return join_char.join(string_or_iterable)
TypeError: sequence item 4: expected str instance, int found
```

caused by:
```
keywords: [Debian, QNAP, TS-409, Orion, 5281]
```

5281 is interpreted as an integer instead of a string.  I wonder if all keywords should be converted to strings.

**Comment by ralsina** [comment]
Yeah, all strings makes sense.

**Comment by felixfontein** [comment]
How about changing `smartjoin` as follows:
- if the input is an array or iterable, convert all arguments to strings with `str()` and join them;
- if the input is anything else, apply `str()` and return it.

This is a bit more general, and won't fail if the input happens to be an integer instead of a string (which can happen with other metadata formats, and keywords/tags such as `404`).

**Comment by Kwpolska** [comment]
@felixfontein :+1:

Anyone wants to do this?

**Comment by felixfontein** [comment]
I'll do it.

**Comment by tbm** [comment]
Thank you @Kwpolska and @felixfontein!
