### ISSUE TITLE
Issue with tag similarity

### ISSUE THREAD

**Issue by ChillarAnand** [getnikola/nikola#3123]
### Environment (if reporting a bug)

**Python Version:** 3.7

**Nikola Version:** 7.8.15

**Operating System:** ubuntu 18.04

### Description:

When writing articles in english language, I would like to use `telugu` as tag and when writing in Telugu language, I would like to use `తెలుగు` as tag so that people who want to read Telugu articles can filter with `తెలుగు` tag. 

```
[2018-07-25T16:48:43Z] ERROR: auto: Scanning posts.......[2018-07-25T16:48:42Z] ERROR: Nikola: You have tags that are too similar: తెలుగు and telugu
```

Nikola treats both as same. Is there an easy way to prevent this?

**Comment by ralsina** [comment]
Well, not an easy one :-)

I suspect this is because to determine similarity we are looking at
slugified tags.

Basically,

>>> slugify('తెలుగు')
'telugu'

So, that would mean that both tags would generate the same files. On the
other hand, if you set USE_SLUGIFY to False, then we should not check
slugified tags and the filenames should use the telugu characters.
Can you try with that option set to False? If it still breaks, then it's a
bug.

**Comment by ralsina** [comment]
Also, that check in nikola.py seems redundant since there is a similar one in the taxonomy classificator.

**Comment by ralsina** [comment]
Hey @ChillarAnand looks like removing the redundant check lets a smarter one do the job ... and it seems to work when tags that slugify similarly are used only on different languages!

Also, I can confirm that on our master branch as of right now you can have those two tags at the same time with USE_SLUGIFY = False.

However, keep in mind that using that setting is potentially a cause for weird things, depending on how your system/web server/universe is configured.
