### ISSUE TITLE
shortcode in rst grid table breaks table

### ISSUE THREAD

**Issue by RobinD42** [getnikola/nikola#3213]
### Environment

**Python Version:** 3.6

**Nikola Version:** 8.0.1

**Operating System:** macOS

### Description:

When I use a shortcode inside of an ReST grid table it results in a docutils malformed table error, presumably because the rendering of the shortcode changes the lengths of those lines that ReST sees, and so the grid lines no longer line up.

**Comment by ralsina** [comment]
This is almost impossible to get right. We could adjust the table's column widths to fix the misalignment caused by the shortcode (theoretically! It looks almost impossible to me), but that would make the columns change widths and the resulting HTML table will be deformed anyway.

I suggest that if you want to use shortcodes in tables in reSt you use a [list table](http://docutils.sourceforge.net/docs/ref/rst/directives.html#list-table) ... those should be much more resilient, even though you can **still** break them by having newlines in the output of the shortcode.
