### ISSUE TITLE
Feature Request: I want to support the gitment comment system

### ISSUE THREAD

**Issue by dingpengyu** [getnikola/nikola#3227]
### Environment
**Python Version:**
python3.7.2 32bit
**Nikola Version:**
nikola8.0.1
**Operating System:**
Lenovo Saver Notebook
windows10-180964bit
### Description:
Recently discovered a set of commenting system based on GitHub issue, gitment. Can the official support it? Here is the official GitHub repository:
https://github.com/imsun/gitment
@ralsina

**Comment by dingpengyu** [comment]
Thanks to Kwpolska for fixing the question tag. Does this comment system have the value of support?

**Comment by Kwpolska** [comment]
I don’t think it’s worth adding support in core. Feel free to add it to your own site, but supporting a comment system in core means that we will take care of it and make sure it works — and we aren’t good at that when it comes to using stuff we don’t. (Notice that Isso got more usable yesterday with #3225/#3226 only because I switched my blog to it.)

**Comment by ralsina** [comment]
Just as a footnote:

Using this in a static site (and I suspect everywhere) implies putting a GH oauth secret in plain view, so it sounds like a very bad idea.
