### ISSUE TITLE
Teaser for ipynb posts 

### ISSUE THREAD

**Issue by parisni** [getnikola/nikola#3256]
for RST posts, it is possible to create a "end teaser" keyword which allows not to share the wall post.

I haven't seen this for ipynb based posts yet. I suggest to add such  metadata in the notebook.

for example:

```
  "nikola": {
   "category": "",
   "date": "2019-05-05 13:58:47 UTC+02:00",
   "description": "",
   "link": "",
   "slug": "my_post",
   "tags": "",
   "title": "My Post",
   "type": "text"
   "endTeaser": 4
  }
```

this would only show the first 4 cells of the notebook.

**Comment by Kwpolska** [comment]
You can just use `<!-- TEASER_END -->` in a Markdown cell to use the standard teaser mechanism. It looks well if you put it at the end of a cell with text, and becomes slightly ugly only if it’s a cell all by itself. But I would suspect that most people would want to end their teasers with/before some text, not in the middle of code.

Supporting this would require substantial effort and code changes, and might not even be possible, because the splitting is done after the post has already been rendered to HTML.
