### ISSUE TITLE
How to get rid of default (base) theme assets?

### ISSUE THREAD

**Issue by Xeverous** [getnikola/nikola#3281]
I'm using my own theme and what interests me is why does Nikola copy some additional CSS and JS files to the output?

```
.  copy_assets:output/assets/js/baguetteBox.min.js
.  copy_assets:output/assets/js/html5shiv-printshiv.min.js
.  copy_assets:output/assets/js/fancydates.min.js
.  copy_assets:output/assets/js/gallery.js
.  copy_assets:output/assets/js/justified-layout.min.js
.  copy_assets:output/assets/js/gallery.min.js
.  copy_assets:output/assets/js/fancydates.js
.  copy_assets:output/assets/js/moment-with-locales.min.js
.  copy_assets:output/assets/js/html5.js
.  copy_assets:output/assets/xml/rss.xsl
.  copy_assets:output/assets/xml/atom.xsl
.  copy_assets:output/assets/css/ipython.min.css
.  copy_assets:output/assets/css/rst_base.css
.  copy_assets:output/assets/css/baguetteBox.min.css
.  copy_assets:output/assets/css/rst.css
.  copy_assets:output/assets/css/nikola_ipython.css
.  copy_assets:output/assets/css/html4css1.css
.  copy_assets:output/assets/css/theme.css
.  copy_assets:output/assets/css/nikola_rst.css
.  copy_assets:output/assets/css/code.css
.  render_galleries:output/galleries/index.html
.  render_galleries:output/galleries/rss.xml
```

My theme does not contain any such files and my CSS and JS has no dependencies. Is this all from the "base" theme? How can I get rid of it? https://getnikola.com/theming.html#theme-meta-files says:

> "The parent is so you don’t have to create a full theme each time: just create an empty theme, set the parent, and add the bits you want modified. You **must** define a parent, otherwise many features won’t work due to missing templates, messages, and assets."

Is there any way I can get rid of these files and have a really "clean, actually empty base" theme? I don't care about losing some built-in features.

**Comment by Kwpolska** [comment]
Yes, those files are part of the base theme. You might not need them all now, but if you ever change your mind, it will be easier to get them back. Those files don’t weigh much, and you can remove references from the template code not to load them.

That said, we do have an option for this: put `ignored_assets=comma,separated,list` in your `.theme` file. It’s [here](https://github.com/getnikola/nikola/blob/f0db0f270a5561e56205c72841cec5900a8c49d9/nikola/plugins/task/copy_assets.py#L69) in the code. It’s not documented, and I don’t expect it to be, because this can easily break stuff.

The only mandatory asset on the list is `rst_base.css` if you’re using reST for your posts; the rest can be deleted if you are 100% sure you aren’t using them.

**Comment by Xeverous** [comment]
This sounds like some unwanted built-in limitation. I picked up Nikola because it has very plugin-like structure and allows to customize every build step.

But this is the first time I see a framework which does not actually has a build in "empty theme" where actually no templates/JS/CSS exists.

> It’s not documented, and I don’t expect it to be, because this can easily break stuff.

What stuff could be broken? Does Nikola assume certain things are present in every theme? If so, that sounds for me against its design where everything is "plugin-replacable".

**Comment by Kwpolska** [comment]
> This sounds like some unwanted built-in limitation. I picked up Nikola because it has very plugin-like structure and allows to customize every build step.

We have to strike a balance between pluggability and needless complexity. We could make it possible to kill everything related to galleries when you disable galleries, but that would require substantial effort just to save a few kilobytes.

> But this is the first time I see a framework which does not actually has an "empty theme" where actually no base templates/JS/CSS exists and everything is picked from framework user data.

Nikola isn’t a framework in the traditional sense. A Nikola site works out of the box. We put assets in `base` because most people will want to use them on their sites, no matter the theme.

> What stuff could be broken? Does Nikola assume certain things are present in every theme? If so, that sounds for me against its design where everything is "plugin-replacable".

Authors of themes in themes.getnikola.com should not use the ignore option, because that limits their theme usability substantially, and we don’t want that.

> Would it be possible to have something like parent = None work and just use only what is provided by the user?

You can create a theme with no `parent` specified (no line for `parent=`) and Nikola won’t complain. But note that you will need to provide all `.tmpl` files expected by the plugins your site uses and the `messages` folder (symlinking to `base` in cases where you don’t want to roll your own stuff should work just fine).

**Comment by Xeverous** [comment]
> You can create a theme with no parent specified (no line for parent=) and Nikola won’t complain.

I have tried it but it looks like something is still expected. Unless - do I need to remove something from `conf.py`?

```
Scanning posts........done!
[2019-08-04T20:32:02Z] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
[2019-08-04T20:32:02Z] ERROR: Nikola: jinja2.exceptions.TemplateNotFound: list_post.tmpl
```

> But note that you will need to provide all .tmpl files expected by the plugins your site uses

I'm fine with this. I have so unique needs that no one would really want to reuse them. My plugins can be completely tied to my own theme.

> and the messages folder

I don't under this. What exactly is the purpose of messages?

**Comment by Kwpolska** [comment]
The `list_post.tmpl` template is expected by the built-in taxonomies plugins that are enabled on your site. You can disable them with the DISABLED_PLUGINS setting in `conf.py`.

---

The messages folder is used for all visitor-facing strings in Nikola to allow for translations.  Messages are used by some of the built-in themes and plugins.  We require at least `messages_en` to be available.

**Comment by Xeverous** [comment]
Ok, I did `nikola plugin --list` and got the list of all plugins. I will disable everything that I don't need that would cause some unsatisfied dependency requirements.

If I need something in the future, I will enable it back. I prefer the "start from empty state" approach to avoid any unwanted side effects or unused data (working in embedded...).

**Comment by Kwpolska** [comment]
`nikola plugin --list` gives you a list of plugins available for install from plugins.getnikola.com.  We don’t have any command to list built-in plugins. You can get their names from the `ini` files though:

```
$ grep -i '^name' nikola/plugins/{misc,shortcode,task}/*.plugin
misc/scan_posts.plugin:Name = scan_posts
misc/taxonomies_classifier.plugin:name = classify_taxonomies
shortcode/chart.plugin:name = chart
shortcode/emoji.plugin:name = emoji
shortcode/gist.plugin:name = gist
shortcode/listing.plugin:name = listing_shortcode
shortcode/post_list.plugin:name = post_list
shortcode/thumbnail.plugin:name = thumbnail
task/archive.plugin:name = classify_archive
task/authors.plugin:Name = classify_authors
task/bundles.plugin:name = create_bundles
task/categories.plugin:name = classify_categories
task/copy_assets.plugin:name = copy_assets
task/copy_files.plugin:name = copy_files
task/galleries.plugin:name = render_galleries
task/gzip.plugin:name = gzip
task/indexes.plugin:name = classify_indexes
task/listings.plugin:name = render_listings
task/page_index.plugin:name = classify_page_index
task/pages.plugin:name = render_pages
task/posts.plugin:name = render_posts
task/redirect.plugin:name = redirect
task/robots.plugin:name = robots
task/scale_images.plugin:name = scale_images
task/sitemap.plugin:name = sitemap
task/sources.plugin:name = render_sources
task/tags.plugin:name = classify_tags
task/taxonomies.plugin:name = render_taxonomies
```

**Comment by Xeverous** [comment]
Ok, that will help.

**Comment by ralsina** [comment]
Create a theme, don't inherit any parent theme, that's it.

It will be a ton of work to make it work, tho.
