### ISSUE TITLE
Provide conda packages

### ISSUE THREAD

**Issue by deeplook** [getnikola/nikola#3283]
I'm looking for conda packages, but can find only pretty old ones here: https://anaconda.org/search?q=nikola. Any plans to provide more recent ones regularly?

**Comment by ralsina** [comment]
I don't think @Kwpolska uses Conda, and I know I don't. Volunteers doing it have included @damianavila and @asmeurer ... is there anything I can do to make it easier?

Can it be automated?

**Comment by damianavila** [comment]
I should probably take the lead here... I have Nikola conda packages in my channel (I created manually a long time ago). IIRC, there was an issue already opened about this. I am rising now the priority of this task in my todo list, although not sure when I can get some time to make it happen.

> Can it be automated?

Yep, we need to make it available through [conda-forge](https://conda-forge.org/).
The pipeline is there, in fact, I use it for one of my popular projects: https://github.com/conda-forge/rise-feedstock.

**Comment by Kwpolska** [comment]
Is a conda package for Nikola really useful and needed? It's a pure Python
package, and most (if not all) of our dependencies are either pure or have
prebuilt wheels on PyPI. You can just use pip install in a conda
environment.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by deeplook** [comment]
@Kwpolska 1. Conda is simply the more mature package manager (pip is an installer) that has become the standard for data science (see [conda vs pip](https://www.anaconda.com/understanding-conda-and-pip/)). 2. [Pelican](https://anaconda.org/conda-forge/pelican) already provides conda packages.

**Comment by Kwpolska** [comment]
@deeplook 
pip had 1.0 in [2011](https://github.com/pypa/pip/blob/cb00488ca66acdeaae4b4353d1d8bdadc6340dce/NEWS.rst#10-2011-04-04), conda in [2012](https://github.com/conda/conda/blob/1d0e23ed17a8f050051ae911b21f4ef22f8c6277/CHANGELOG.md#2012-09-06---100). pip has more contributors than Conda, and more users (not everyone uses Anaconda/does data science). Furthermore, pip is also a package manager, it has `uninstall` and `search` options.

Conda’s main argument used to be “binary packages for everything”, but the introduction of wheels to pip has made it less relevant.  Nowadays, you can `pip install Nikola` on Windows, macOS and Linux without needing a C compiler, since all our dependencies have wheels.

To be clear, I’m not against providing Conda packages, if:  
(a) there are volunteers to do this, or  
(b) there are ways to automate the creation of Conda packages, which do not require installing and maintaining a copy of Anaconda/Minicoda by the maintainers.

**Comment by bashtage** [comment]
I use conda to provide Python, but it is really simple to do something like

```bash
conda create -n nikola python=3.7
conda activate nikola
pip install 'Nikola[extras]"
```

I'm not sure what the gain is to have a conda package given that most dependencies are pure python and those that are not use multibuild and so have binaries available for Win/Linux/OSX.

**Comment by damianavila** [comment]
> I'm not sure what the gain is to have a conda package given that most dependencies are pure python and those that are not use multibuild and so have binaries available for Win/Linux/OSX.

I would answer that with this:

> (b) there are ways to automate the creation of Conda packages, which do not require installing and maintaining a copy of Anaconda/Minicoda by the maintainers.

Conda-forge does this. This is why I have this one in my todo list, but the list is long :wink:

**Comment by ralsina** [comment]
Proposed it in conda-forge because why not.

https://github.com/conda-forge/staged-recipes/pull/11292

**Comment by ralsina** [comment]
Annnnd no idea why it fails. It was worth a try, I guess.

**Comment by ralsina** [comment]
So, apparently you need to specify each dependency in the conda build, and they need to be already packaged for conda. This is both stupid and useless:

* It's a source of errors, since we would need to maintain dependencies in two places
* It's not doable now (yapsy is not packaged, not going down that rabbit hole)
* It provides no value whatsoever to any user

If someone wants Nikola inside conda, he's free to install it there using pip, as suggested in previous comments.

**Comment by damianavila** [comment]
> So, apparently you need to specify each dependency in the conda build, and they need to be already packaged for conda. 

I actually did the work for an old version Nikola version: https://anaconda.org/damianavila82/repo
But those were manually created, not through conda-forge.
Eventually, I will create recipes for any needed package in conda-forge, and I will come back here and comment about the good news :wink:

In the meantime...

> If someone wants Nikola inside conda, they are free to install it there using pip, as suggested in previous comments.

**Comment by ickc** [comment]
Package now live at https://anaconda.org/conda-forge/nikola

**Comment by Kwpolska** [comment]
(Please note that `pip` is still the official recommended install method, even if you are using Conda.)

**Comment by deeplook** [comment]
@ickc Thanks! It's hard to explain the advantages of conda/mamba to people not using them, yet. Pip is an installer/uninstaller, but doesn't care (much? enough? at all?) about dependency consistency.

**Comment by Kwpolska** [comment]
@deeplook You don’t need to care about dependency consistency if you use a dedicated virtual environment for Nikola. Also, pip’s dependency situation has been improving, and there are third-party tools that extend/build upon pip with better dependency and environment management capabilities.

**Comment by ickc** [comment]
No solution is perfect but conda definitely has its advantages. Lickily as always dev need not to support every platform out there and there's package maintainers supporting other packaging system.

Just to name one problem with pip, you can't manage non Python dependencies. Conda is a general package manager, while popular for Python stack, is beyond that. One example in Nikola's dep is pandoc. In conda it is trivial to include pandoc as an (optionally optional) dep which Eg if a certain nikola version only support pandoc 2.11 you can constrain that, and you just can't do that in pip. This is speaking from someone managing pandoc stack such as panflute and pantable, etc that heavily depends on pandoc's API.

**Comment by deeplook** [comment]
@Kwpolska I _do_ care about dependency consistency, but I expect this from a true package _manager_, which, for me, pip is not. And I got too used to installing stuff like emacs, rust, openjdk, etc. with conda/mamba and don't want to miss that anymore. If pip suits you, that's fine. I'm not evangelizing this further, if I ever did before.

**Comment by ickc** [comment]
@deeplook,

@Kwpolska didn't mean that dependency consistency is not important, his statement is "if you use a dedicated virtual environment for Nikola" is good enough for dependency consistency.

*I think* it is a big IF, and betting on pip's on-going improvement is not good enough to settle for it at the moment.

I also think that not supporting that officially is no big deal. There's many packages in many managers that are not supported by the upstream, and they works fine, some better even than the upstream.

Also, for pure Python dev it is often hard for them to see the advantages of conda/mamba. (Although Nikola does have non-python dep such as pandoc.) It is just another extra work without clear benefit (surely they should have a PyPI package before putting it in conda-forge.)

**Comment by ickc** [comment]
Also, by distributing on PyPI they are doing an important work to support it indirectly—as long as their sdist is correct, which is what the conda-forge package depends on, it should just works. (It also involves translating the dep from `setup.py` to `meta.yml`, but potential human errors here are protected by `pip --check`.)

**Comment by damianavila** [comment]
@ickc thanks for working on this one. It is nice to have Nikola conda packages available from conda-forge.
So I guess you built recipes for all the missing dependencies as well, right?
I did that manually some time ago but I never migrated them into conda-forge because of lack of time...

**Comment by ickc** [comment]
All mandatory dependencies are already in conda-forge. A few extras dependencies are still in PR waiting for review. One involves ghp-import2 is blocking as mentioned in #3499

**Comment by damianavila** [comment]
> All mandatory dependencies are already in conda-forge.

Ja... that was not the case some years ago... nice to see that!

**Comment by asmeurer** [comment]
How does the conda-forge package work with Nikola[extras]?  Nikola has so many optional dependencies that I usually just install that as I don't want to worry about which ones I actually use or might use.

**Comment by ickc** [comment]
> Ja... that was not the case some years ago... nice to see that!

No, I meant I added them.

**Comment by ickc** [comment]
> How does the conda-forge package work with Nikola[extras]? Nikola has so many optional dependencies that I usually just install that as I don't want to worry about which ones I actually use or might use.

Conda (and conda-forge) works differently. Optional dep. are set up as "run constraints", where only if you install it in your environment it will be constrained by the specified ineq. So there's no shortcut like `nikola[extras]`, you have to enumerate all of them.

See <https://github.com/conda-forge/nikola-feedstock/blob/master/recipe/meta.yaml#L43-L58>.

**Comment by ickc** [comment]
Example file:

```yaml
name: nikola
channels:
  - conda-forge
dependencies:
  - python=3.9
  - nikola
  - ghp-import
  - jinja2
  - aiohttp
  - watchdog
  - ruamel.yaml
  - html5lib
  - pantable
```

And run

```bash
conda env create -f FILE.yml
```

**Comment by asmeurer** [comment]
It would be useful to either have a metapackage for nikola-extra, or else just include those in the dependencies of the main nikola package.

**Comment by ickc** [comment]
I don't think the 2nd choice is a good solution as it mandates more than one need.

The first may be good solution, but I'm not aware of other people packaging their extras as a separate metapackage. Could you give some example? Also, I'm not sure if the conda-forge admin will accept this if this is not standard practice.

This is not something I'd worry about though, because the packaging step is already done, and also because it is not a wildly popular way of installing nikola nor something the upstream officially support or endorse. The important thing about packaging is to make sure if they indeed install the optional dependencies, it will be of the correct version as specified in `setup.py`.

**Comment by ickc** [comment]
May be another way to put it is that **if** the conda-forge package is officially supported/endorsed, then any "unexpected" feature in the conda package can be mentioned specifically in the doc. e.g. asking people to "`conda install nikola-extras` if you want everything", or simply mention "if you `conda install nikola` it will gives you all the extras."

But because it isn't (in the doc), creating meta packages is only going to cause confusion. Without additional doc, I'd expect the package in conda-forge exactly reflect `setup.py`—what's mandatory is mandatory, what's optional if installed will be of correct version, etc.

**Comment by ickc** [comment]
All extra dependencies are constrained in conda: https://github.com/conda-forge/nikola-feedstock/pull/3, except ghp-import2 are dropped-in with ghp-import instead as conda-forge won't accept ghp-import2: https://github.com/conda-forge/staged-recipes/pull/13605#issuecomment-761232010

**Comment by asmeurer** [comment]
@ickc I'm not too familiar with the feature, but you may be able to use the outputs feature to create a `nikola-extras` metapackage that depends on everything https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section. If you have any questions, I would make an issue on the nikola feedstock and CC the conda-forge maintainers. Either way, we should move the discussion to the feedstock repository.
