### ISSUE TITLE
Reduce dependency footprint

### ISSUE THREAD

**Issue by ghost** [getnikola/nikola#3333]
Nikola currently has 26 dependencies, including these:

~~~
Babel
blinker
docutils
doit
logbook
mako
Markdown
natsort
piexif
Pygments
PyRSS2Gen
python-dateutil
requests
setuptools
unidecode
Yapsy
~~~

and these transitive:

~~~
certifi (from requests)
chardet (from requests)
cloudpickle (from doit)
idna (from requests)
MarkupSafe (from mako)
pytz (from Babel)
six (from python-dateutil)
urllib3 (from requests)
~~~

and these native extensions:

~~~
Pillow
lxml
~~~

could some of these be removed? I know personally I dont have any use for the
Pillow imaging library and maybe some others.

**Comment by ralsina** [comment]
Yes, you do need the Pillow extension if you want to have images in your
website.

**Comment by cup** [comment]
@ralsina I dont think thats true. My understanding is Pillow would only be needed if you wish to do image manipulation. If you merely have images that are already processed, I cant imagine how Pillow would be needed.

**Comment by ralsina** [comment]
Nikola processes images. Last I checked you can actually remove Pillow and
end with a less functional installation if you want

**Comment by cup** [comment]
@ralsina something like this:

~~~diff
diff --git a/requirements-extras.txt b/requirements-extras.txt
index 62de7ce..db6f87d 100644
--- a/requirements-extras.txt
+++ b/requirements-extras.txt
@@ -15,2 +15,4 @@ ruamel.yaml>=0.15
 toml>=0.9.2

+Pillow>=2.4.0
+lxml>=3.3.5
diff --git a/requirements.txt b/requirements.txt
index 805f780..b8fd84d 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,5 +1,4 @@
 doit>=0.30.1
 Pygments>=1.6
-Pillow>=2.4.0
 python-dateutil>=2.6.0
 docutils>=0.13
@@ -7,5 +6,4 @@ mako>=1.0.0
 Markdown>=3.0.0
 unidecode>=0.04.16
-lxml>=3.3.5
 Yapsy>=1.11.223
 PyRSS2Gen>=1.1
~~~

**Comment by ralsina** [comment]
I would rather not. Pillow is needed for image galleries and image
thumbnails and both are core features.

**Comment by Kwpolska** [comment]
lxml is mandatory for HTML processing. All pages we render go through that.

-- 
Chris Warrick <https://chriswarrick.com/>

**Comment by Kwpolska** [comment]
A lot of the dependencies may not be required for a specific site, but we prefer to have support for a slightly larger feature set out of the box (unlike other SSGs, which prefer a bare-bones approach), and the feature set includes code listings, images/galleries, feeds, and i18n, among others.

- doit>=0.30.1 — for just about everything (handles building the site in an incremental way)
- Pygments>=1.6 — for code listings, which appear often on blogs of our target audience
- Pillow>=2.4.0 — for image processing, which is pretty important on many websites, and galleries are a pretty important feature
- python-dateutil>=2.6.0 — for processing dates in posts, timezones, and a few other datetime-related niceties
- docutils>=0.13 — reST is the default input format
- mako>=1.0.0 — default template engine
- Markdown>=3.0.0 — Markdown is also enabled by default
- unidecode>=0.04.16 — produces good slugs for i18n posts
- lxml>=3.3.5 — HTML processing
- Yapsy>=1.11.223 — plugin system
- PyRSS2Gen>=1.1 — RSS generation
- logbook>=1.3.0 — slightly better logging
- blinker>=1.3 — signal handlers, useful for plugins
- setuptools>=24.2.0 — we use some modern setuptools features when installing and at runtime, ~every Python distro ships with setuptools
- natsort>=3.5.2 — natural sorting of strings with numbers appears in quite a few places
- requests>=2.2.0 — plugin/theme installers + some shortcodes and compiler extensions
- piexif>=1.0.3 — galleries/image processing, EXIF filtering is a must these days
- Babel>=2.6.0 — high-quality i18n support (our previous implementation based on the `locale` module was very unstable and dependent on OSes, which didn’t always provide the best data)

Transitive dependencies: there is no way to get rid of them, really. Most of them are small anyway. We have two timezone things due to this (dateutil and pytz), but we need dateutil’s other features, and we need Babel’s good i18n stuff, so it has to stay.

Native extensions: those aren’t really a problem nowadays. Binary wheels are available for both lxml and Pillow, for the supported versions of Python, for Windows, macOS and Linux, and for i686 and x86_64.  This only leaves ARM on Linux (which doesn’t have the manylinux binary standard set for yet) and *BSDs (where you probably have a working compiler setup anyway).

Out of this list, there only dependency I could imagine getting rid of is logbook.  We don’t really use any of its advanced features anymore, so we could switch over to the standard `logging` module with just a few adjustments (namely, replace the `NOTICE` level with `WARNING`, possibly patch it in for plugins, do our own coloring and handler management, and that’s basically it)

Another one could be Blinker, but that would only be doable with a new major version, since changing over to a custom implementation would require plugins to follow suit.

**Comment by cup** [comment]
I use Cygwin, which does have `python3-lxml` but not Pillow, which means I have to build it.

**Comment by Kwpolska** [comment]
In that case, you could try to get rid of Pillow as @ralsina mentioned.  Pillow was made mandatory in #3330, but you could patch it out manually or provide a mock `PIL` module to keep Nikola happy.   Do note that we support running on Windows natively, that could make stuff easier.

**Comment by ralsina** [comment]
Let's close this, I don't think we have any dependencies that need removing. Agree @Kwpolska ?

**Comment by Kwpolska** [comment]
Yeah, we can’t really improve this. The only other dependency we theoretically could tackle is `blinker`, but that would be a v9 thing, unless we want to do ugly sys.modules patching.
