### ISSUE TITLE
Math in post titles not rendered with MathJax on tag posts list

### ISSUE THREAD

**Issue by alusiani** [getnikola/nikola#3427]
### Environment

**Python Version:** 3.8.3

**Nikola Version:** 8.1.0

**Operating System:** Fedora 32

### Description:

I use math in post titles (with "has_math: true"). Math is rendered correctly with MathJax when on the specific page, and also when all posts are shown, but it is not rendered with MathJax when a list of posts containing a tag is displayed.

This is the offending page in my web site: https://precision-sm.github.io/tags/babar/ .

The relevant page is displayed OK with rendered math at https://precision-sm.github.io/posts/BaBar-ep-em-to-pip-pim/ .

On the page sources, I note that the "MathJax.Hub.Config ..." text fragment I enable in conf.py for rendering math inside $$ is reported once at the beginning of the page where math is not rendered, and is reported twice, a second time towards the end, on the page that works correctly.

The whole source of my website can be found at: https://github.com/precision-sm/precision-sm.github.io

Thanks for this very nice piece of software! Best regards,

Alberto Lusiani

**Comment by Kwpolska** [comment]
1. The repeated mathjax config is a (minor) bug. (Leaving bug open to track the fix.)
2. The tag page lacks `MathJax.js`, which is used to render math. We only load MathJax on pages that need it (posts that have `has_math` and indexes with those posts), because MathJax is quite big and can break pages unaware of it.
3. You could disable the conditional load and always load MathJax. This would work, but you are still giving raw TeX to RSS users, and it’s still in the `<title>` tag. (The same thing happens if you try to use HTML in a post title.)
4. A better solution would be to use only plain-text in post titles. Unicode is okay in titles, so if you replace \pi with π, you can get something more portable.

**Comment by alusiani** [comment]
Thanks for the quick reply!

The recommendation not to user math in post titles is fair.

Perhaps, since there is only partial functionality for math in titles, the fact that math is not rendered on tags pages to minimize the load for whoever reads that sort of feed could me mentioned in the documentation.

**Comment by Kwpolska** [comment]
I added a small note to docs and fixed the duplicate config in #3430.
