### ISSUE TITLE
nbconvert 6 and jinja2.exceptions.TemplateNotFound: static/style.css

### ISSUE THREAD

**Issue by shahinrostami** [getnikola/nikola#3457]
### Environment

**Python Version:** 3.8.5, 3.7.9

**Nikola Version:** 8.1.1 and 8.0.4

**Operating System:** Windows 10, WSL2 (running through miniconda on ubuntu)

### Description:

Hello - I'd like to raise this issue unless it's been resolved since 8.1.1 (current version on PyPI).

When running `nikola build` or `nikola build -a` with all cache deleted, the following error comes up when starting to process `.ipynb` posts:

```jinja2.exceptions.TemplateNotFound: static/style.css```

This worked for me prior to a system factory reset and reinstallation of software, so I started downgrading to versions I knew worked, e.g. python 3.8.5 to 3.7.9 and Nikola 8.1.1 to 8.0.4 in hopes of a quick fix. I couldn't find much through a web search, most of it referred to Flask.

I was checking the versions of Jinja2 and nbconvert in hopes of finding something there, and I noticed that `nbconvert` was at `6.0.2`. I downgraded it to a version I knew worked, `5.6.1`, and everything is running smoothly again!

**Comment by Kwpolska** [comment]
nbconvert broke compatibility with the template names we used in v6, and the changes aren’t fully documented (see jupyter/nbconvert#1384). I created PR #3458 with a fix, please test.

**Comment by shahinrostami** [comment]
> 
> 
> nbconvert broke compatibility with the template names we used in v6, and the changes aren’t fully documented (see [jupyter/nbconvert#1384](https://github.com/jupyter/nbconvert/issues/1384)). I created PR #3458 with a fix, please test.

Tested and confirmed. Great work - thank you.

**Comment by mattnicholson38** [comment]
Hi,

I'm certainly a newbie, but I don't think this bug is completely fixed.  I get a very similar error almost out of the box running the nikola demo site configured to add .ipynb posts:

jinja2.exceptions.TemplateNotFound: basic.tpl

Downgrading to nbconvert 5.6.1 as suggested above solved the problem.  Pretty painful for a newbie, but did get me to install Ubuntu (thinking it was a Windows thing, ha)

Python Version: 3.8.5
Nikola Version: 8.1.1
Operating Systems: Windows 10 and Ubuntu under VirtualBox (identical results)

**Comment by Kwpolska** [comment]
Hi @mattnicholson38!

This bug was fixed, and the fix was committed to this repository. However, there has been no release of Nikola since then. Installing Nikola with `pip install Nikola` will still install v8.1.1, which has the bug. You can install the [git version](https://getnikola.com/getting-started.html#installGitHub) or manually patch `ipynb.py` with the fixes in PR #3458.

(A new release is probably overdue, I will try to allocate some time to work on that and a few outstanding issues soon.)
