### ISSUE TITLE
Error when using LINK_CHECK_WHITELIST

### ISSUE THREAD

**Issue by stsewd** [getnikola/nikola#3466]
### Environment

**Python Version:** 3.8

**Nikola Version:** 8.1

**Operating System:** Linux

### Description:

When using

```python
LINK_CHECK_WHITELIST = [
    r'http://127\.0\.0\.1',
]
```

And running `nikola check -l`, you get

```
[2020-10-10 10:31:23] ERROR: check: Error with: .../index.html cannot use a string pattern on a by
tes-like object

```

Looks like the bug is around here

https://github.com/getnikola/nikola/blob/38bd1c08e50b36da3c7bd9e7c3fbeccdddb0cd61/nikola/plugins/command/check.py#L276-L278

But I'm not familiar enough with the codebase to know why target is a byte string or where that conversion is happening.

**Comment by Kwpolska** [comment]
This is coming from: https://github.com/getnikola/nikola/blob/38bd1c08e50b36da3c7bd9e7c3fbeccdddb0cd61/nikola/plugins/command/check.py#L351-L352

This bug was there since April 2013, and it probably worked with Python 2. It probably never worked right with Python 3, which suggests nobody used this feature… Fix in PR #3467, please test.
