### ISSUE TITLE
auto feature broken with aiohttp 3.7.0

### ISSUE THREAD

**Issue by bhartshorn** [getnikola/nikola#3470]
### Environment

**Python Version:** 3.8.6

**Nikola Version:** v8.1.1 installed via pip in venv

**Operating System:** Arch Linux

### Description:
It seems that the version 3.7.0 of `aiohttp` - released ~18 hours ago - is not supported.  I'm seeing this error when running `nikola auto`:

```
[2020-10-24 21:49:47] ERROR: Nikola: In order to use the "auto" command, you must install the "aiohttp" Python package.
[2020-10-24 21:49:47] ERROR: Nikola: Exiting due to missing dependencies.
```
After explicitly installing aiohttp 3.6.2, `nikola auto` runs as expected.

**Comment by Kwpolska** [comment]
This seems to be caused by a bug in `aiohttp==3.7.0`, which needs `typing_extensions` but fails to declare it as a dependency. `aiohttp==3.7.1` has been released, and this error doesn’t occur (I also can’t reproduce if I manually downgrade to 3.7.0 without removing `typing_extensions`). See aio-libs/aiohttp#5107.
