### ISSUE TITLE
Documentation: clarify connection between DEPLOY_DRAFTS and USE_TAG_METADATA

### ISSUE THREAD

**Issue by jwhendy** [getnikola/nikola#3478]
I used nikola some time ago, but just updated and went through some woes of migrating my old `conf.py` to the new. It's been so long I completely forgot the settings I'd used on my site.

A post I'd tagged `draft` was still getting published, and [the documentation](https://nikola.readthedocs.io/en/latest/manual/#drafts) clarified how to stop that:
>If you add a “draft” tag to a post, then it will not be shown in indexes and feeds. It will be compiled, and if you deploy it it will be made available, so use with care. If you wish your drafts to be not available in your deployed site, you can set `DEPLOY_DRAFTS = False` in your configuration.

That said, it appears that this default `conf.py` setting renders that ineffective:
```
# If set to True, the tags 'draft', 'mathjax' and 'private' have special
# meaning. If set to False, these tags are handled like regular tags.
USE_TAG_METADATA = False
```

I searched the page for "tag_metadata" and get no hits. Would you consider adding a clarification or breadcrumb link to the `USE_TAG_METADATA` setting?

**Comment by Kwpolska** [comment]
It looks like you’re reading a very old version of the documentation. Here is what the docs say as of 2018-04-27 (commit 4d6010c4a2):

> If you set the ``status`` metadata field of a post to ``draft``, it will not be shown
in indexes and feeds. It *will* be compiled, and if you deploy it it *will* be made
available, so use with care. If you wish your drafts to be not available in your
deployed site, you can set ``DEPLOY_DRAFTS = False`` in your configuration. This will
not work if you include ``nikola build`` in your ``DEPLOY_COMMANDS``, as the
option removes the draft posts before any ``DEPLOY_COMMANDS`` are run.

The setting `USE_TAG_METADATA` is a backwards compatibility setting. Because of this, we default to `True`, and override it as `False` in `conf.py.in` (note that it’s uncommented). Not all Nikola options are documented in the manual, and not all should be (the manual is already very long, that would be completely unsustainable). We expect most users not to enable this option, unless they have a legacy unconverted site.

You might want to read the [Upgrading to Nikola v8](https://getnikola.com/blog/upgrading-to-nikola-v8.html) document, it does mention this change, the `upgrade_metadata_v8` plugin that can help you fix other posts on your site, and perhaps other things.

**Comment by jwhendy** [comment]
Interesting. Sorry about that, and I'm still not sure how that happened. I specifically clicked "latest" at the bottom to make sure (same link as above that I quoted):

https://nikola.readthedocs.io/en/latest/manual/#drafts

Searching "nikola documentation" shows that site with the title 8.1.1:
![grab_2020-11-15_151316](https://user-images.githubusercontent.com/379357/99197003-33d17300-2755-11eb-96eb-2e5b43ae4497.png)

Clicking through from there to drafts takes me to the same as above. The other [main documentation site](https://getnikola.com/documentation.html) also links there:

> Here is all the documentation for Nikola. Note that it applies to the latest release, so it may not be accurate if you’re using an older version, or are using an unstable version. If you want to read the documentation for the current GitHub master, check out [Nikola on ReadTheDocs](https://nikola.readthedocs.io/en/latest/). Clicking "edit on github" takes me [here](https://github.com/getnikola/nikola/blob/master/docs/sphinx/index.rst).

I haven't dug around to know where those should post, but perhaps something is still awry here?

---

For my issue, I was able to set `USE_TAG_METADATA` back to false, switching to the new tags instead for `drafts` and `use-math`. Thanks for the assistance.

**Comment by Kwpolska** [comment]
That’s how this page looks on my side:

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/327323/99198091-a1ea5a00-2796-11eb-91d5-cfe7a7e65136.png">

Perhaps your browser has a really old cache?

**Comment by jwhendy** [comment]
Wow, facepalm. I indeed see `status` instead of `tag`, but I think it just didn't register in my mind as "different enough" so I thought I was still seeing my original quote. Apologies for the noise.
