### ISSUE TITLE
align option for table directive

### ISSUE THREAD

**Issue by nickvence** [getnikola/nikola#3486]
### Environment

**Python Version:** 3.8.5

**Nikola Version:** 8.1.2

**Operating System:** macOS 10.14.6

### Description:
As a teacher, I want images and tables right-justified with explanatory text flowing around them on the left.
I was happy to find that 

    .. image:: http://www.gmtgames.com/nnhis/cover.jpg
        :align: right

accomplished this.
Unfortunately, the table generated by the following code

    .. table:: My Table
        :align: right
        :width: 30%

        =====  =====
          A    not A
        =====  =====
        False  True
        True   False
        =====  =====
is not floated; that is, there is a large block of whitespace to the table's left.

Would you fix the align option to the table directive so that the text flows around it?
Thanks in advance,
Nick Vence

**Comment by Kwpolska** [comment]
1. The `table` directive is provided by docutils. We use their styles for this, and if anyone was to change it, it would be the docutils team — and I doubt they would, since many users depend on the current behavior.
2. You can use `:class: float-right` to get the behavior you want (at least bootblog4). You can also create your own CSS class for this and assign any other styles you want those tables to have (a margin on the left?)
