### ISSUE TITLE
The feed pages use semantically incorrect `<input>` to show the feed url

### ISSUE THREAD

**Issue by nimaje** [getnikola/nikola#3521]
### Description:

The feed pages use semantically incorrect `<input>` to show the feed url, as nothing happens if you press enter or change it, it is clearly not an `<input>`, so something else should be used there.

How about `<a>`?

The files that would need to be changed are:
nikola/data/themes/base/assets/xml/atom.xsl
nikola/data/themes/base/assets/xml/rss.xsl

**Comment by ralsina** [comment]
There is no <input> anywhere in the generated RSS at least (checked my own
site: http://ralsina.me/rss.xml)

**Comment by nimaje** [comment]
It's in the xsl stylesheet, if you look at the feed with a browser you will see an input box

**Comment by ralsina** [comment]
Ah, I see.

**Comment by Kwpolska** [comment]
If you end up on that page, you probably want to copy it to your RSS reader of choice. `<input>` makes this operation very easy, since you can just use Ctrl-A inside the box to do the right thing. With `<a>`, you get a link that your web browser isn’t going to help with, and you need to either right-click and copy the destination address, or do a precise selection with a mouse.

**Comment by ralsina** [comment]
It was added intentionally by the person doing the XSL support, wonder why.

https://github.com/getnikola/nikola/commits/b90364eb66cfc513c440ba2aa0f258387716f1da/nikola/data/themes/base/assets/xml/atom.xsl

**Comment by nimaje** [comment]
well, than at least `readonly="readonly"` should be set.

**Comment by Kwpolska** [comment]
Closing as won’t fix, it’s a super minor thing and I’d consider a regular input more convenient.
