### ISSUE TITLE
Improved navigation links / menus

### ISSUE THREAD

**Issue by JeppeKlitgaard** [getnikola/nikola#3531]
I recently started toying with Nikola and I am quite impressed with it.

It appears that there isn't support for a creating a submenu, where the main label is itself a link. Perhaps there is a way to do this that I have simply missed? It would be fairly easy to make a quick hack in my template, but I am wondering if it would be beneficial to make the `NAVIGATION_LINKS` configuration slightly more advanced?

This would likely not be possible to implement in a backwards-compatible way, but maybe it could be added to the Nikola 9 roadmap? If this were to be implemented, support for more than 1 level of submenu might also be added (like now it would ultimately be up to themes whether to support this or not).

I am happy to take a stab at it myself, if this is a feature that is actually wanted.

Example
---

* "Posts"  --> `/posts/`
* -- "Tech" --> `/posts/tech`
* -- "Politics" --> `/posts/politics`

**Comment by sukiletxe** [comment]
How would you distinguish between expanding the submenu and opening the link in that scenario? How would you do so without using a mouse ?(Blind people like me usually don't hover over a link to see if ther's anything in there, unless we're consciously looking for something which isn't there, then we resort to hovering).

**Comment by Kwpolska** [comment]
This feature would require support from a theme. Bootstrap doesn’t seem to support this in the navbar, so we won’t change this for the bootstrap family (and thus the core). You can build your own theme that supports links in dropdowns just fine, since the `NAVIGATION_LINKS` structure can be anything you want, so you can extend it for your custom theme to add a link to the item title.

(You could also build some sort of ugly hack in Bootstrap with a blank menu title, but I wouldn’t recommend that for accessibility and visual reasons.)

**Comment by JeppeKlitgaard** [comment]
I hadn't actually thought about this from an accessibility standpoint, nor was I aware that Bootstrap (seemingly intentionally) doesn't support this. 

Realising that, I think I'll opt for an approach that works within the existing framework. Thanks for your swift feedback!
