### ISSUE TITLE
MathJax loads on site index if a post with "has_math: true" is shown, without checking for LaTeX visibility

### ISSUE THREAD

**Issue by 000yesnt** [getnikola/nikola#3669]
### Environment

**Python Version:** Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32

**Nikola Version:** 8.2.3

**Operating System:** Windows 10 10.0.19045.2604

### Description:

When a post with the `has_math: true` metadata field is shown on the site index, MathJax is loaded regardless of whether there's any visible LaTeX, wasting bandwidth.

For example, with index teasers enabled and `END_TEASER` placed before the math directive, MathJax loads. This also seems to happen when a post has no content, but `has_math` is on.

No other settings were changed; this is a fully stock Nikola site.

Screenshots:
![Case: No posts with has_math enabled](https://user-images.githubusercontent.com/49329895/224535172-0150169b-b46c-42cd-a3a1-527d743489b1.png)

![Case: one post with has_math enabled](https://user-images.githubusercontent.com/49329895/224535188-a9af9fbb-df9e-4722-bb40-50155dec6451.png)

![Case: contentless post with has_math enabled](https://user-images.githubusercontent.com/49329895/224535559-f190bef6-7996-4069-9c3a-66ba3e2687c5.png)

**Comment by Kwpolska** [comment]
Thanks for reporting this, but we can’t fix this in any good way.

* For us to know whether or not the teaser contains math, we would need to parse the post contents and look for math delimiters.
* Nikola supports custom MathJax/KaTeX configurations, and there are example alternate configurations in conf.py, which means that we would need to parse those configurations (which can be arbitrary JS code) to figure out what delimiters to use.
* MathJax/KaTeX might also have other rules that cause them to convert (e.g. class="math"?) or skip (escapes? code/pre?) something.
* This means that we need to duplicate MathJax/KaTeX’s logic (and note that they might have different behaviour) and we need a JS parser for the delimiter configuration.
* This quickly becomes costly and error-prone. This is also why we expect the author to just tell us if they’re using math or not instead of trying to guess.
* I also believe this is a problem only in edge cases. A post with `has_math` but no math (or no content at all) is perhaps the user’s mistake. A post with `has_math` but all math appearing outside of the teaser would be the only relevant case (and something that might happen in real life, especially if the teasers are short or if there isn’t much math in the post in the first place). But, as mentioned before, there is no way for us to reliably determine this.
* The bandwidth cost is quite small (78.6 kB on your screenshots), and we always use MathJax/KaTeX from a CDN, so this bandwidth does not come out of your server anyway.
* If this is common on your blog, you can do some customizations to fix this. If you never use math in teasers, you could disable the inclusion of MathJax/KaTeX in `math_scripts_ifposts` and `math_styles_ifposts` in `math_helper.tmpl`. If you use math only in a handful of teasers, you could add a custom metadata field (`teaser_has_math`) and modify those functions to check the new field.
