### ISSUE TITLE
XMPP: Post to PubSub

### ISSUE THREAD

**Issue by sjehuda** [getnikola/nikola#3771]
**Requested Feature:** (short description)
I want to publish my Nikola contents over PubSub node items on my XMPP server.

**Related Area:** (eg. tasks, compilers, configuration, templates…)
Templates as Atom Syndication Format (RFC 4287)

**Do you want to contribute this yourself as a pull request?** (don’t worry about it if you don’t want to/can’t — someone else can take care of it)

- [x] Yes, I have written a proof of concept code from which we can learn.
- [ ] Yes, I have already written code for it (link if available and feasible)
- [ ] Yes, I don’t have code ready yet (that’s okay!)
- [ ] No (that’s okay too!)

**Does this feature affect backwards compatibility? If yes, in what way?**
No

**Rationale and full description:**

In XMPP, using PubSub(1) (XEP-0060), it is possible to store posts as Atom Syndication(2) entries into XMPP(3).

There are several XMPP extensions that apply it, namely XEP-0227 (4) and XEP-0472 (5) which make node `xmpp:microblog:0` as a common choice to manage news for client accounts (e.g. `blog@getnikola.com`), yet a component account (e.g. `pubsub.getnikola.com`) may use all of its nodes for this purpose.

```
pubsub.getnikola.com/
|
|-- updates/
    |-- Sombre
     `-- Varied
|-- releases/
 `-- events/
```

```
pubsub service/
|
|-- node/
    |-- item
     `-- item
|-- node/
 `-- node/
```

I have made a script that realizes viewing PubSub node items as Atom XML feeds over HTTP.

1. [XEP-0060: Publish-Subscribe](https://xmpp.org/extensions/xep-0060.html)
2. [RFC 4287: The Atom Syndication Format](https://www.rfc-editor.org/rfc/rfc4287)
3. [Atom Over XMPP](https://datatracker.ietf.org/meeting/66/materials/slides-66-atompub-1.pdf)
4. [XEP-0277: Microblogging over XMPP](https://xmpp.org/extensions/xep-0277.html)
5. [XEP-0472: Pubsub Social Feed](https://xmpp.org/extensions/xep-0472.html)
6. [PubSub Over HTTP](https://codeberg.org/poezio/slixmpp/issues/3526)

**Why should it be added to Nikola?**
Because it would allow everyone - even those who do not have their own servers nor websites - to publish using Nikola.

**Comment by Kwpolska** [comment]
1. Nikola is a blog generator. The primary purpose of Nikola is generating a website. Nikola is not going to start generating some obscure XMPP thing now.
2. Speaking of obscure XMPP things, nobody uses XMPP these days. The list of users who would be interested in an XMPP thing would be very low and not worth a full overhaul of Nikola.
3. I can see that you spammed at least 15 other repositories with the same issue, which means you are not genuinely interested in having Nikola do this.

**Comment by sjehuda** [comment]
> Nikola is a blog generator. The primary purpose of Nikola is generating a website. Nikola is not going to start generating some obscure XMPP thing now.

I understand that, yet, supporting PubSub is really supporting Atom and RSS. It is an XML form which is sent to an XMPP server.

Atom is an XML form sent over HTTP.
PubSub is an XML form sent over XMPP.

The [script I have made](https://codeberg.org/poezio/slixmpp/issues/3526)  shows how little effort is required to utilize PubSub.

> Speaking of obscure XMPP things, nobody uses XMPP these days. The list of users who would be interested in an XMPP thing would be very low and not worth a full overhaul of Nikola.

XMPP is used more and more, even today.
If you would check Movim, you will see the potential the PubSub system has to offer.

> I can see that you spammed at least 15 other repositories with the same issue, which means you are not genuinely interested in having Nikola do this.

1. I am not hiding my activity, even though I can.
2. I am interested in every CMS to do this.
3. It would make a wonders to sharing textual articles and posts.

---

Please reconsider.

Thank you.

**Comment by Kwpolska** [comment]
> I understand that, yet, supporting PubSub is really supporting Atom and RSS. It is an XML form which is sent to an XMPP server.
>
> Atom is an XML form sent over HTTP.
> PubSub is an XML form sent over XMPP.

Okay. Nikola supports Atom and RSS since time immemorial. What exactly is required?

> The [script I have made](https://codeberg.org/poezio/slixmpp/issues/3526) shows how little effort is required to utilize PubSub.

The issue you linked to is titled *Documentation: Add examples of using slixmpp as an object running _in the background_*. This code seems like a PubSub->Atom translator, and I’m not sure how it would be relevant to Nikola, and I’m still not sure what the requested feature is.

Nikola is not something you actually run on a server. Nikola is a static site generator that you can run on any computer (most likely your workstation, not a server), and the output can be deployed anywhere. Nikola blogs can be served by GitHub Pages, nginx/apache running on a $5 VPS, or a shared web hosting with FTP as the sole upload interface (party like it’s 2005). The audience of Nikola are people who are capable of and comfortable with running a command-line Python program somewhere and distributing its output around. Is the feature you want to add compatible with static site generators?

> XMPP is used more and more, even today.

[citation needed]

---

Neither of your two comments actually describes what feature you want added. Nikola has a plugin-based model of development, so if your idea is compatible with a static site generators, you should first start by implementing it as a plugin and contributing it to getnikola/plugins. Adding a new complex core feature is something we want to limit. We are open to accepting pull requests that add extensibility points required by your plugin if some are required.

**Comment by sjehuda** [comment]
May I move this issue to /getnikola/plugins ?
