### ISSUE TITLE
Atom feeds support

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#899]
Via [Google Groups thread](https://groups.google.com/forum/#!topic/nikola-discuss/DzWoP9O8KrM) by Saadat M.

Requires a migration to a different generator, like feedgenerator (used by Django and Pelican).

//cc @Aeyoun

**Comment by Aeyoun** [comment]
Check out branch task-atom. Not sure if anyone else would find this useful? It’s paginated Atom syndication and Atom archives for old pages. For indexes and tag/category indexes. Extended indexes instead of making it a separate plugin as its just an alternate presentation of existing index pages. Only exposed to consumers through HTML auto-discovery and the sitemapindex.

**Comment by Aeyoun** [comment]
Nikola 7.4.0 has Atom feed for indexes.
