### ISSUE TITLE
hreflang rel=alternate is not implemented for galleries and tags

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#993]
cc @Aeyoun.

I did something very dumb.  I misunderstood how _link works in our templates, thus leading to a big failure for people with localized sites (like @smartass101).  Long story short:

``` pytb
########################################
TaskError - taskid:render_galleries:output/galleries/index.html
PythonAction Error
Traceback (most recent call last):
  File "/home/kwpolska/virtualenvs/nikola-py2/lib/python2.7/site-packages/doit/action.py", line 360, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/kwpolska/git/nikola/nikola/plugins/task/galleries.py", line 466, in render_gallery_index
    self.site.render_template(template_name, output_name, context)
  File "/home/kwpolska/git/nikola/scripts/../nikola/nikola.py", line 607, in render_template
    template_name, None, local_context)
  File "/home/kwpolska/git/nikola/nikola/plugins/template/mako.py", line 88, in render_template
    data = template.render_unicode(**context)
  File "/home/kwpolska/virtualenvs/nikola-py2/lib/python2.7/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/home/kwpolska/virtualenvs/nikola-py2/lib/python2.7/site-packages/mako/runtime.py", line 807, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/kwpolska/virtualenvs/nikola-py2/lib/python2.7/site-packages/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/kwpolska/virtualenvs/nikola-py2/lib/python2.7/site-packages/mako/runtime.py", line 865, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/kwpolska/Desktop/nikola-translated-path/cache/.mako.tmp/base.tmpl.py", line 91, in render_body
    __M_writer(unicode(base.meta_translations()))
  File "/home/kwpolska/Desktop/nikola-translated-path/cache/.mako.tmp/base_helper.tmpl.py", line 274, in render_meta_translations
    __M_writer(unicode(_link(permalink, None, langname)))
  File "/home/kwpolska/git/nikola/scripts/../nikola/nikola.py", line 765, in link
    return self.path(*args, is_link=True)
  File "/home/kwpolska/git/nikola/scripts/../nikola/nikola.py", line 729, in path
    path = self.path_handlers[kind](name, lang)
KeyError: u'/galleries/galleries/index.html'
```

I tried to use `permalink` as the first argument to _link.  That doesn’t work, we need to do more checking.  Thus, the feature is currently removed.  We need to find a better way.

**Comment by ralsina** [comment]
I don't quite understand what this bug is... is it about adding links to translated RSS feeds to tags and gallery pages?

**Comment by Kwpolska** [comment]
It’s about adding this:

```html
<link rel="alternate" hreflang="es" href="/es/categories/foo.html">
```

to `/categories/foo.html` (and also other languages, tags and galleries)

**Comment by ralsina** [comment]
Ok.

**Comment by ralsina** [comment]
The part that's not done of this issue is doing it for taxonomies ... I can't really follow that code very well. Maybe @felixfontein ?

**Comment by felixfontein** [comment]
I don't think it makes sense to add this for tags, categories or sections, as there is no reason why the same tag/category/section name should be used in more than one language. I'd rather have this links point to the correct translation, but that needs more knowledge.

**Comment by ralsina** [comment]
@felixfontein closing this then.

**Comment by felixfontein** [comment]
It definitely does make sense for archives, and for section indexes. Maybe I can try something out this evening or so.

Let's not close this yet :)

**Comment by felixfontein** [comment]
I'd like to add some brainstorming for adding such functionality for categories, tags and sections. I don't think I'll try that today (except including some basics which allow adding that later more easily), but it won't hurt to write down some thoughts. Maybe someone wants to comment on this as well :)

It would make sense to allow the user to link tags in different languages together, like the following:
```
TAG_TRANSLATIONS = [
  {'en': 'cars', 'de': 'autos', 'fr': 'voitures'},
  {'en': 'windows', 'de': 'fenster', 'fr': 'fenêtre'},  # the things in the wall
  {'en': 'windows', 'de': 'windows', 'fr': 'windows'},  # the operating system
  {'en': 'cakes', 'de': 'kuchen'},
]
```
In this case, the english tag page for `windows` has two sets of other language links for `de` and `fr`, because there are two possible matches. Also, `cakes` will only have one link for `de`, but none for `fr` as there is no French equivalent mentioned. This makes code a bit more complex, but I think we should support this flexibility. **Any opinions on this?**

There should also be a possibility to add default links between tags of the same name:
```
TAG_TRANSLATION_ADD_DEFAULTS = True
```
If this is set and if there are tags `personal` used for languages `en` and `de`, for example, Nikola should act like `{'en': 'personal', 'de': 'personal'}` was added to `TAG_TRANSLATIONS`.

For some people, enabling this default setting will be perfect (and I guess that was original the intention of this issue). For some others (like me), there's no need to enable the default setting, and they can explicitly specify which tags belong together.

**Comment by ralsina** [comment]
@felixfontein looks like a lot of work and config for something that is not actually visible. If this could also add the visible translation links then maybe it would be worth it.

**Comment by felixfontein** [comment]
Ah, yes, that should of course also be visible :) Otherwise it would really be way too much work for little effect. I apparently didn't look too closely at your changes, I though they were both visible links and invisible ones...

**Comment by felixfontein** [comment]
#2778 now also includes code for authors, categories, tags and sections.

**Comment by ralsina** [comment]
So @felixfontein is there something still missing?

**Comment by felixfontein** [comment]
Yes, some details, and improved feed links (linking to alternatives). I'll probably be able to do that tomorrow or later today.
